// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package pluginrpc

import (
	"fmt"
	"math"

	"github.com/golang/protobuf/proto"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{0}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (dst *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(dst, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{1}
}
func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (dst *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(dst, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

type KillRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillRequest) Reset()         { *m = KillRequest{} }
func (m *KillRequest) String() string { return proto.CompactTextString(m) }
func (*KillRequest) ProtoMessage()    {}
func (*KillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{2}
}
func (m *KillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillRequest.Unmarshal(m, b)
}
func (m *KillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillRequest.Marshal(b, m, deterministic)
}
func (dst *KillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillRequest.Merge(dst, src)
}
func (m *KillRequest) XXX_Size() int {
	return xxx_messageInfo_KillRequest.Size(m)
}
func (m *KillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KillRequest proto.InternalMessageInfo

type KillResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillResponse) Reset()         { *m = KillResponse{} }
func (m *KillResponse) String() string { return proto.CompactTextString(m) }
func (*KillResponse) ProtoMessage()    {}
func (*KillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{3}
}
func (m *KillResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillResponse.Unmarshal(m, b)
}
func (m *KillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillResponse.Marshal(b, m, deterministic)
}
func (dst *KillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillResponse.Merge(dst, src)
}
func (m *KillResponse) XXX_Size() int {
	return xxx_messageInfo_KillResponse.Size(m)
}
func (m *KillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KillResponse proto.InternalMessageInfo

type CollectRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectRequest) Reset()         { *m = CollectRequest{} }
func (m *CollectRequest) String() string { return proto.CompactTextString(m) }
func (*CollectRequest) ProtoMessage()    {}
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{4}
}
func (m *CollectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectRequest.Unmarshal(m, b)
}
func (m *CollectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectRequest.Marshal(b, m, deterministic)
}
func (dst *CollectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectRequest.Merge(dst, src)
}
func (m *CollectRequest) XXX_Size() int {
	return xxx_messageInfo_CollectRequest.Size(m)
}
func (m *CollectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectRequest proto.InternalMessageInfo

func (m *CollectRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type CollectResponse struct {
	MetricSet            []*Metric  `protobuf:"bytes,1,rep,name=metric_set,json=metricSet,proto3" json:"metric_set,omitempty"`
	Warnings             []*Warning `protobuf:"bytes,2,rep,name=warnings,proto3" json:"warnings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CollectResponse) Reset()         { *m = CollectResponse{} }
func (m *CollectResponse) String() string { return proto.CompactTextString(m) }
func (*CollectResponse) ProtoMessage()    {}
func (*CollectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{5}
}
func (m *CollectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectResponse.Unmarshal(m, b)
}
func (m *CollectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectResponse.Marshal(b, m, deterministic)
}
func (dst *CollectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectResponse.Merge(dst, src)
}
func (m *CollectResponse) XXX_Size() int {
	return xxx_messageInfo_CollectResponse.Size(m)
}
func (m *CollectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectResponse proto.InternalMessageInfo

func (m *CollectResponse) GetMetricSet() []*Metric {
	if m != nil {
		return m.MetricSet
	}
	return nil
}

func (m *CollectResponse) GetWarnings() []*Warning {
	if m != nil {
		return m.Warnings
	}
	return nil
}

type LoadCollectorRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JsonConfig           []byte   `protobuf:"bytes,2,opt,name=json_config,json=jsonConfig,proto3" json:"json_config,omitempty"`
	MetricSelectors      []string `protobuf:"bytes,3,rep,name=metric_selectors,json=metricSelectors,proto3" json:"metric_selectors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadCollectorRequest) Reset()         { *m = LoadCollectorRequest{} }
func (m *LoadCollectorRequest) String() string { return proto.CompactTextString(m) }
func (*LoadCollectorRequest) ProtoMessage()    {}
func (*LoadCollectorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{6}
}
func (m *LoadCollectorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadCollectorRequest.Unmarshal(m, b)
}
func (m *LoadCollectorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadCollectorRequest.Marshal(b, m, deterministic)
}
func (dst *LoadCollectorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadCollectorRequest.Merge(dst, src)
}
func (m *LoadCollectorRequest) XXX_Size() int {
	return xxx_messageInfo_LoadCollectorRequest.Size(m)
}
func (m *LoadCollectorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadCollectorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadCollectorRequest proto.InternalMessageInfo

func (m *LoadCollectorRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *LoadCollectorRequest) GetJsonConfig() []byte {
	if m != nil {
		return m.JsonConfig
	}
	return nil
}

func (m *LoadCollectorRequest) GetMetricSelectors() []string {
	if m != nil {
		return m.MetricSelectors
	}
	return nil
}

type LoadCollectorResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadCollectorResponse) Reset()         { *m = LoadCollectorResponse{} }
func (m *LoadCollectorResponse) String() string { return proto.CompactTextString(m) }
func (*LoadCollectorResponse) ProtoMessage()    {}
func (*LoadCollectorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{7}
}
func (m *LoadCollectorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadCollectorResponse.Unmarshal(m, b)
}
func (m *LoadCollectorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadCollectorResponse.Marshal(b, m, deterministic)
}
func (dst *LoadCollectorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadCollectorResponse.Merge(dst, src)
}
func (m *LoadCollectorResponse) XXX_Size() int {
	return xxx_messageInfo_LoadCollectorResponse.Size(m)
}
func (m *LoadCollectorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadCollectorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadCollectorResponse proto.InternalMessageInfo

type UnloadCollectorRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnloadCollectorRequest) Reset()         { *m = UnloadCollectorRequest{} }
func (m *UnloadCollectorRequest) String() string { return proto.CompactTextString(m) }
func (*UnloadCollectorRequest) ProtoMessage()    {}
func (*UnloadCollectorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{8}
}
func (m *UnloadCollectorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnloadCollectorRequest.Unmarshal(m, b)
}
func (m *UnloadCollectorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnloadCollectorRequest.Marshal(b, m, deterministic)
}
func (dst *UnloadCollectorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnloadCollectorRequest.Merge(dst, src)
}
func (m *UnloadCollectorRequest) XXX_Size() int {
	return xxx_messageInfo_UnloadCollectorRequest.Size(m)
}
func (m *UnloadCollectorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnloadCollectorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnloadCollectorRequest proto.InternalMessageInfo

func (m *UnloadCollectorRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type UnloadCollectorResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnloadCollectorResponse) Reset()         { *m = UnloadCollectorResponse{} }
func (m *UnloadCollectorResponse) String() string { return proto.CompactTextString(m) }
func (*UnloadCollectorResponse) ProtoMessage()    {}
func (*UnloadCollectorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{9}
}
func (m *UnloadCollectorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnloadCollectorResponse.Unmarshal(m, b)
}
func (m *UnloadCollectorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnloadCollectorResponse.Marshal(b, m, deterministic)
}
func (dst *UnloadCollectorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnloadCollectorResponse.Merge(dst, src)
}
func (m *UnloadCollectorResponse) XXX_Size() int {
	return xxx_messageInfo_UnloadCollectorResponse.Size(m)
}
func (m *UnloadCollectorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnloadCollectorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnloadCollectorResponse proto.InternalMessageInfo

type InfoRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{10}
}
func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (dst *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(dst, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

func (m *InfoRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type InfoResponse struct {
	XLegacyInfo          *XLegacyInfo `protobuf:"bytes,1,opt,name=_legacy_info,json=LegacyInfo,proto3" json:"_legacy_info,omitempty"`
	Info                 []byte       `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *InfoResponse) Reset()         { *m = InfoResponse{} }
func (m *InfoResponse) String() string { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()    {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{11}
}
func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse.Unmarshal(m, b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
}
func (dst *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(dst, src)
}
func (m *InfoResponse) XXX_Size() int {
	return xxx_messageInfo_InfoResponse.Size(m)
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func (m *InfoResponse) GetXLegacyInfo() *XLegacyInfo {
	if m != nil {
		return m.XLegacyInfo
	}
	return nil
}

func (m *InfoResponse) GetInfo() []byte {
	if m != nil {
		return m.Info
	}
	return nil
}

type PublishRequest struct {
	TaskId               string    `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	MetricSet            []*Metric `protobuf:"bytes,2,rep,name=metric_set,json=metricSet,proto3" json:"metric_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{12}
}
func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (dst *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(dst, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *PublishRequest) GetMetricSet() []*Metric {
	if m != nil {
		return m.MetricSet
	}
	return nil
}

type PublishResponse struct {
	Warnings             []*Warning `protobuf:"bytes,1,rep,name=warnings,proto3" json:"warnings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PublishResponse) Reset()         { *m = PublishResponse{} }
func (m *PublishResponse) String() string { return proto.CompactTextString(m) }
func (*PublishResponse) ProtoMessage()    {}
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{13}
}
func (m *PublishResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishResponse.Unmarshal(m, b)
}
func (m *PublishResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishResponse.Marshal(b, m, deterministic)
}
func (dst *PublishResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishResponse.Merge(dst, src)
}
func (m *PublishResponse) XXX_Size() int {
	return xxx_messageInfo_PublishResponse.Size(m)
}
func (m *PublishResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublishResponse proto.InternalMessageInfo

func (m *PublishResponse) GetWarnings() []*Warning {
	if m != nil {
		return m.Warnings
	}
	return nil
}

type LoadPublisherRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JsonConfig           []byte   `protobuf:"bytes,2,opt,name=json_config,json=jsonConfig,proto3" json:"json_config,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadPublisherRequest) Reset()         { *m = LoadPublisherRequest{} }
func (m *LoadPublisherRequest) String() string { return proto.CompactTextString(m) }
func (*LoadPublisherRequest) ProtoMessage()    {}
func (*LoadPublisherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{14}
}
func (m *LoadPublisherRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadPublisherRequest.Unmarshal(m, b)
}
func (m *LoadPublisherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadPublisherRequest.Marshal(b, m, deterministic)
}
func (dst *LoadPublisherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadPublisherRequest.Merge(dst, src)
}
func (m *LoadPublisherRequest) XXX_Size() int {
	return xxx_messageInfo_LoadPublisherRequest.Size(m)
}
func (m *LoadPublisherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadPublisherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadPublisherRequest proto.InternalMessageInfo

func (m *LoadPublisherRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *LoadPublisherRequest) GetJsonConfig() []byte {
	if m != nil {
		return m.JsonConfig
	}
	return nil
}

type LoadPublisherResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadPublisherResponse) Reset()         { *m = LoadPublisherResponse{} }
func (m *LoadPublisherResponse) String() string { return proto.CompactTextString(m) }
func (*LoadPublisherResponse) ProtoMessage()    {}
func (*LoadPublisherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{15}
}
func (m *LoadPublisherResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadPublisherResponse.Unmarshal(m, b)
}
func (m *LoadPublisherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadPublisherResponse.Marshal(b, m, deterministic)
}
func (dst *LoadPublisherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadPublisherResponse.Merge(dst, src)
}
func (m *LoadPublisherResponse) XXX_Size() int {
	return xxx_messageInfo_LoadPublisherResponse.Size(m)
}
func (m *LoadPublisherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadPublisherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadPublisherResponse proto.InternalMessageInfo

type UnloadPublisherRequest struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnloadPublisherRequest) Reset()         { *m = UnloadPublisherRequest{} }
func (m *UnloadPublisherRequest) String() string { return proto.CompactTextString(m) }
func (*UnloadPublisherRequest) ProtoMessage()    {}
func (*UnloadPublisherRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{16}
}
func (m *UnloadPublisherRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnloadPublisherRequest.Unmarshal(m, b)
}
func (m *UnloadPublisherRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnloadPublisherRequest.Marshal(b, m, deterministic)
}
func (dst *UnloadPublisherRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnloadPublisherRequest.Merge(dst, src)
}
func (m *UnloadPublisherRequest) XXX_Size() int {
	return xxx_messageInfo_UnloadPublisherRequest.Size(m)
}
func (m *UnloadPublisherRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnloadPublisherRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnloadPublisherRequest proto.InternalMessageInfo

func (m *UnloadPublisherRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type UnloadPublisherResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnloadPublisherResponse) Reset()         { *m = UnloadPublisherResponse{} }
func (m *UnloadPublisherResponse) String() string { return proto.CompactTextString(m) }
func (*UnloadPublisherResponse) ProtoMessage()    {}
func (*UnloadPublisherResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{17}
}
func (m *UnloadPublisherResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnloadPublisherResponse.Unmarshal(m, b)
}
func (m *UnloadPublisherResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnloadPublisherResponse.Marshal(b, m, deterministic)
}
func (dst *UnloadPublisherResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnloadPublisherResponse.Merge(dst, src)
}
func (m *UnloadPublisherResponse) XXX_Size() int {
	return xxx_messageInfo_UnloadPublisherResponse.Size(m)
}
func (m *UnloadPublisherResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnloadPublisherResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnloadPublisherResponse proto.InternalMessageInfo

type Metric struct {
	Namespace            []*Namespace      `protobuf:"bytes,1,rep,name=namespace,proto3" json:"namespace,omitempty"`
	Value                *MetricValue      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp            *Time             `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Description          string            `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Unit                 string            `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{18}
}
func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (dst *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(dst, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetNamespace() []*Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *Metric) GetValue() *MetricValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Metric) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Metric) GetTimestamp() *Time {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Metric) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Metric) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

type Namespace struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}
func (*Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{19}
}
func (m *Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespace.Unmarshal(m, b)
}
func (m *Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespace.Marshal(b, m, deterministic)
}
func (dst *Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespace.Merge(dst, src)
}
func (m *Namespace) XXX_Size() int {
	return xxx_messageInfo_Namespace.Size(m)
}
func (m *Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_Namespace proto.InternalMessageInfo

func (m *Namespace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Namespace) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Namespace) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type MetricValue struct {
	// Types that are valid to be assigned to DataVariant:
	//	*MetricValue_VFloat
	//	*MetricValue_VDouble
	//	*MetricValue_VInt32
	//	*MetricValue_VInt64
	//	*MetricValue_VUint32
	//	*MetricValue_VUint64
	//	*MetricValue_VBool
	//	*MetricValue_VBytes
	//	*MetricValue_VString
	DataVariant          isMetricValue_DataVariant `protobuf_oneof:"data_variant"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MetricValue) Reset()         { *m = MetricValue{} }
func (m *MetricValue) String() string { return proto.CompactTextString(m) }
func (*MetricValue) ProtoMessage()    {}
func (*MetricValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{20}
}
func (m *MetricValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricValue.Unmarshal(m, b)
}
func (m *MetricValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricValue.Marshal(b, m, deterministic)
}
func (dst *MetricValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricValue.Merge(dst, src)
}
func (m *MetricValue) XXX_Size() int {
	return xxx_messageInfo_MetricValue.Size(m)
}
func (m *MetricValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricValue.DiscardUnknown(m)
}

var xxx_messageInfo_MetricValue proto.InternalMessageInfo

type isMetricValue_DataVariant interface {
	isMetricValue_DataVariant()
}

type MetricValue_VFloat struct {
	VFloat float32 `protobuf:"fixed32,1,opt,name=v_float,json=vFloat,proto3,oneof"`
}

type MetricValue_VDouble struct {
	VDouble float64 `protobuf:"fixed64,2,opt,name=v_double,json=vDouble,proto3,oneof"`
}

type MetricValue_VInt32 struct {
	VInt32 int32 `protobuf:"varint,3,opt,name=v_int32,json=vInt32,proto3,oneof"`
}

type MetricValue_VInt64 struct {
	VInt64 int64 `protobuf:"varint,4,opt,name=v_int64,json=vInt64,proto3,oneof"`
}

type MetricValue_VUint32 struct {
	VUint32 uint32 `protobuf:"varint,5,opt,name=v_uint32,json=vUint32,proto3,oneof"`
}

type MetricValue_VUint64 struct {
	VUint64 uint64 `protobuf:"varint,6,opt,name=v_uint64,json=vUint64,proto3,oneof"`
}

type MetricValue_VBool struct {
	VBool bool `protobuf:"varint,7,opt,name=v_bool,json=vBool,proto3,oneof"`
}

type MetricValue_VBytes struct {
	VBytes []byte `protobuf:"bytes,8,opt,name=v_bytes,json=vBytes,proto3,oneof"`
}

type MetricValue_VString struct {
	VString string `protobuf:"bytes,9,opt,name=v_string,json=vString,proto3,oneof"`
}

func (*MetricValue_VFloat) isMetricValue_DataVariant() {}

func (*MetricValue_VDouble) isMetricValue_DataVariant() {}

func (*MetricValue_VInt32) isMetricValue_DataVariant() {}

func (*MetricValue_VInt64) isMetricValue_DataVariant() {}

func (*MetricValue_VUint32) isMetricValue_DataVariant() {}

func (*MetricValue_VUint64) isMetricValue_DataVariant() {}

func (*MetricValue_VBool) isMetricValue_DataVariant() {}

func (*MetricValue_VBytes) isMetricValue_DataVariant() {}

func (*MetricValue_VString) isMetricValue_DataVariant() {}

func (m *MetricValue) GetDataVariant() isMetricValue_DataVariant {
	if m != nil {
		return m.DataVariant
	}
	return nil
}

func (m *MetricValue) GetVFloat() float32 {
	if x, ok := m.GetDataVariant().(*MetricValue_VFloat); ok {
		return x.VFloat
	}
	return 0
}

func (m *MetricValue) GetVDouble() float64 {
	if x, ok := m.GetDataVariant().(*MetricValue_VDouble); ok {
		return x.VDouble
	}
	return 0
}

func (m *MetricValue) GetVInt32() int32 {
	if x, ok := m.GetDataVariant().(*MetricValue_VInt32); ok {
		return x.VInt32
	}
	return 0
}

func (m *MetricValue) GetVInt64() int64 {
	if x, ok := m.GetDataVariant().(*MetricValue_VInt64); ok {
		return x.VInt64
	}
	return 0
}

func (m *MetricValue) GetVUint32() uint32 {
	if x, ok := m.GetDataVariant().(*MetricValue_VUint32); ok {
		return x.VUint32
	}
	return 0
}

func (m *MetricValue) GetVUint64() uint64 {
	if x, ok := m.GetDataVariant().(*MetricValue_VUint64); ok {
		return x.VUint64
	}
	return 0
}

func (m *MetricValue) GetVBool() bool {
	if x, ok := m.GetDataVariant().(*MetricValue_VBool); ok {
		return x.VBool
	}
	return false
}

func (m *MetricValue) GetVBytes() []byte {
	if x, ok := m.GetDataVariant().(*MetricValue_VBytes); ok {
		return x.VBytes
	}
	return nil
}

func (m *MetricValue) GetVString() string {
	if x, ok := m.GetDataVariant().(*MetricValue_VString); ok {
		return x.VString
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MetricValue) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MetricValue_OneofMarshaler, _MetricValue_OneofUnmarshaler, _MetricValue_OneofSizer, []interface{}{
		(*MetricValue_VFloat)(nil),
		(*MetricValue_VDouble)(nil),
		(*MetricValue_VInt32)(nil),
		(*MetricValue_VInt64)(nil),
		(*MetricValue_VUint32)(nil),
		(*MetricValue_VUint64)(nil),
		(*MetricValue_VBool)(nil),
		(*MetricValue_VBytes)(nil),
		(*MetricValue_VString)(nil),
	}
}

func _MetricValue_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MetricValue)
	// data_variant
	switch x := m.DataVariant.(type) {
	case *MetricValue_VFloat:
		b.EncodeVarint(1<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.VFloat)))
	case *MetricValue_VDouble:
		b.EncodeVarint(2<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.VDouble))
	case *MetricValue_VInt32:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.VInt32))
	case *MetricValue_VInt64:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.VInt64))
	case *MetricValue_VUint32:
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.VUint32))
	case *MetricValue_VUint64:
		b.EncodeVarint(6<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.VUint64))
	case *MetricValue_VBool:
		t := uint64(0)
		if x.VBool {
			t = 1
		}
		b.EncodeVarint(7<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *MetricValue_VBytes:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.VBytes)
	case *MetricValue_VString:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.VString)
	case nil:
	default:
		return fmt.Errorf("MetricValue.DataVariant has unexpected type %T", x)
	}
	return nil
}

func _MetricValue_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MetricValue)
	switch tag {
	case 1: // data_variant.v_float
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.DataVariant = &MetricValue_VFloat{math.Float32frombits(uint32(x))}
		return true, err
	case 2: // data_variant.v_double
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.DataVariant = &MetricValue_VDouble{math.Float64frombits(x)}
		return true, err
	case 3: // data_variant.v_int32
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.DataVariant = &MetricValue_VInt32{int32(x)}
		return true, err
	case 4: // data_variant.v_int64
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.DataVariant = &MetricValue_VInt64{int64(x)}
		return true, err
	case 5: // data_variant.v_uint32
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.DataVariant = &MetricValue_VUint32{uint32(x)}
		return true, err
	case 6: // data_variant.v_uint64
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.DataVariant = &MetricValue_VUint64{x}
		return true, err
	case 7: // data_variant.v_bool
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.DataVariant = &MetricValue_VBool{x != 0}
		return true, err
	case 8: // data_variant.v_bytes
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.DataVariant = &MetricValue_VBytes{x}
		return true, err
	case 9: // data_variant.v_string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.DataVariant = &MetricValue_VString{x}
		return true, err
	default:
		return false, nil
	}
}

func _MetricValue_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MetricValue)
	// data_variant
	switch x := m.DataVariant.(type) {
	case *MetricValue_VFloat:
		n += 1 // tag and wire
		n += 4
	case *MetricValue_VDouble:
		n += 1 // tag and wire
		n += 8
	case *MetricValue_VInt32:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.VInt32))
	case *MetricValue_VInt64:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.VInt64))
	case *MetricValue_VUint32:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.VUint32))
	case *MetricValue_VUint64:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.VUint64))
	case *MetricValue_VBool:
		n += 1 // tag and wire
		n += 1
	case *MetricValue_VBytes:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.VBytes)))
		n += len(x.VBytes)
	case *MetricValue_VString:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.VString)))
		n += len(x.VString)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Time struct {
	Sec                  int64    `protobuf:"varint,1,opt,name=sec,proto3" json:"sec,omitempty"`
	Nsec                 int64    `protobuf:"varint,2,opt,name=nsec,proto3" json:"nsec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{21}
}
func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (dst *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(dst, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetSec() int64 {
	if m != nil {
		return m.Sec
	}
	return 0
}

func (m *Time) GetNsec() int64 {
	if m != nil {
		return m.Nsec
	}
	return 0
}

type Warning struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp            *Time    `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Warning) Reset()         { *m = Warning{} }
func (m *Warning) String() string { return proto.CompactTextString(m) }
func (*Warning) ProtoMessage()    {}
func (*Warning) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{22}
}
func (m *Warning) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Warning.Unmarshal(m, b)
}
func (m *Warning) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Warning.Marshal(b, m, deterministic)
}
func (dst *Warning) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Warning.Merge(dst, src)
}
func (m *Warning) XXX_Size() int {
	return xxx_messageInfo_Warning.Size(m)
}
func (m *Warning) XXX_DiscardUnknown() {
	xxx_messageInfo_Warning.DiscardUnknown(m)
}

var xxx_messageInfo_Warning proto.InternalMessageInfo

func (m *Warning) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Warning) GetTimestamp() *Time {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type XLegacyInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *XLegacyInfo) Reset()         { *m = XLegacyInfo{} }
func (m *XLegacyInfo) String() string { return proto.CompactTextString(m) }
func (*XLegacyInfo) ProtoMessage()    {}
func (*XLegacyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_af2113ffc4edde01, []int{23}
}
func (m *XLegacyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_XLegacyInfo.Unmarshal(m, b)
}
func (m *XLegacyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_XLegacyInfo.Marshal(b, m, deterministic)
}
func (dst *XLegacyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_XLegacyInfo.Merge(dst, src)
}
func (m *XLegacyInfo) XXX_Size() int {
	return xxx_messageInfo_XLegacyInfo.Size(m)
}
func (m *XLegacyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_XLegacyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_XLegacyInfo proto.InternalMessageInfo

func init() {
	proto.RegisterType((*PingRequest)(nil), "pluginrpc.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "pluginrpc.PingResponse")
	proto.RegisterType((*KillRequest)(nil), "pluginrpc.KillRequest")
	proto.RegisterType((*KillResponse)(nil), "pluginrpc.KillResponse")
	proto.RegisterType((*CollectRequest)(nil), "pluginrpc.CollectRequest")
	proto.RegisterType((*CollectResponse)(nil), "pluginrpc.CollectResponse")
	proto.RegisterType((*LoadCollectorRequest)(nil), "pluginrpc.LoadCollectorRequest")
	proto.RegisterType((*LoadCollectorResponse)(nil), "pluginrpc.LoadCollectorResponse")
	proto.RegisterType((*UnloadCollectorRequest)(nil), "pluginrpc.UnloadCollectorRequest")
	proto.RegisterType((*UnloadCollectorResponse)(nil), "pluginrpc.UnloadCollectorResponse")
	proto.RegisterType((*InfoRequest)(nil), "pluginrpc.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "pluginrpc.InfoResponse")
	proto.RegisterType((*PublishRequest)(nil), "pluginrpc.PublishRequest")
	proto.RegisterType((*PublishResponse)(nil), "pluginrpc.PublishResponse")
	proto.RegisterType((*LoadPublisherRequest)(nil), "pluginrpc.LoadPublisherRequest")
	proto.RegisterType((*LoadPublisherResponse)(nil), "pluginrpc.LoadPublisherResponse")
	proto.RegisterType((*UnloadPublisherRequest)(nil), "pluginrpc.UnloadPublisherRequest")
	proto.RegisterType((*UnloadPublisherResponse)(nil), "pluginrpc.UnloadPublisherResponse")
	proto.RegisterType((*Metric)(nil), "pluginrpc.Metric")
	proto.RegisterMapType((map[string]string)(nil), "pluginrpc.Metric.TagsEntry")
	proto.RegisterType((*Namespace)(nil), "pluginrpc.Namespace")
	proto.RegisterType((*MetricValue)(nil), "pluginrpc.MetricValue")
	proto.RegisterType((*Time)(nil), "pluginrpc.Time")
	proto.RegisterType((*Warning)(nil), "pluginrpc.Warning")
	proto.RegisterType((*XLegacyInfo)(nil), "pluginrpc._legacy_info")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error)
}

type controllerClient struct {
	cc *grpc.ClientConn
}

func NewControllerClient(cc *grpc.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/pluginrpc.Controller/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error) {
	out := new(KillResponse)
	err := c.cc.Invoke(ctx, "/pluginrpc.Controller/Kill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
type ControllerServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Kill(context.Context, *KillRequest) (*KillResponse, error)
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginrpc.Controller/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginrpc.Controller/Kill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Kill(ctx, req.(*KillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pluginrpc.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Controller_Ping_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _Controller_Kill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

// CollectorClient is the client API for Collector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CollectorClient interface {
	Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (Collector_CollectClient, error)
	Load(ctx context.Context, in *LoadCollectorRequest, opts ...grpc.CallOption) (*LoadCollectorResponse, error)
	Unload(ctx context.Context, in *UnloadCollectorRequest, opts ...grpc.CallOption) (*UnloadCollectorResponse, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type collectorClient struct {
	cc *grpc.ClientConn
}

func NewCollectorClient(cc *grpc.ClientConn) CollectorClient {
	return &collectorClient{cc}
}

func (c *collectorClient) Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (Collector_CollectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Collector_serviceDesc.Streams[0], "/pluginrpc.Collector/Collect", opts...)
	if err != nil {
		return nil, err
	}
	x := &collectorCollectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Collector_CollectClient interface {
	Recv() (*CollectResponse, error)
	grpc.ClientStream
}

type collectorCollectClient struct {
	grpc.ClientStream
}

func (x *collectorCollectClient) Recv() (*CollectResponse, error) {
	m := new(CollectResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *collectorClient) Load(ctx context.Context, in *LoadCollectorRequest, opts ...grpc.CallOption) (*LoadCollectorResponse, error) {
	out := new(LoadCollectorResponse)
	err := c.cc.Invoke(ctx, "/pluginrpc.Collector/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorClient) Unload(ctx context.Context, in *UnloadCollectorRequest, opts ...grpc.CallOption) (*UnloadCollectorResponse, error) {
	out := new(UnloadCollectorResponse)
	err := c.cc.Invoke(ctx, "/pluginrpc.Collector/Unload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/pluginrpc.Collector/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectorServer is the server API for Collector service.
type CollectorServer interface {
	Collect(*CollectRequest, Collector_CollectServer) error
	Load(context.Context, *LoadCollectorRequest) (*LoadCollectorResponse, error)
	Unload(context.Context, *UnloadCollectorRequest) (*UnloadCollectorResponse, error)
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
}

func RegisterCollectorServer(s *grpc.Server, srv CollectorServer) {
	s.RegisterService(&_Collector_serviceDesc, srv)
}

func _Collector_Collect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CollectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CollectorServer).Collect(m, &collectorCollectServer{stream})
}

type Collector_CollectServer interface {
	Send(*CollectResponse) error
	grpc.ServerStream
}

type collectorCollectServer struct {
	grpc.ServerStream
}

func (x *collectorCollectServer) Send(m *CollectResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Collector_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadCollectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginrpc.Collector/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).Load(ctx, req.(*LoadCollectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collector_Unload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadCollectorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).Unload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginrpc.Collector/Unload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).Unload(ctx, req.(*UnloadCollectorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collector_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginrpc.Collector/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Collector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pluginrpc.Collector",
	HandlerType: (*CollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Load",
			Handler:    _Collector_Load_Handler,
		},
		{
			MethodName: "Unload",
			Handler:    _Collector_Unload_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Collector_Info_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Collect",
			Handler:       _Collector_Collect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

// PublisherClient is the client API for Publisher service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PublisherClient interface {
	Publish(ctx context.Context, opts ...grpc.CallOption) (Publisher_PublishClient, error)
	Load(ctx context.Context, in *LoadPublisherRequest, opts ...grpc.CallOption) (*LoadPublisherResponse, error)
	Unload(ctx context.Context, in *UnloadPublisherRequest, opts ...grpc.CallOption) (*UnloadPublisherResponse, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type publisherClient struct {
	cc *grpc.ClientConn
}

func NewPublisherClient(cc *grpc.ClientConn) PublisherClient {
	return &publisherClient{cc}
}

func (c *publisherClient) Publish(ctx context.Context, opts ...grpc.CallOption) (Publisher_PublishClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Publisher_serviceDesc.Streams[0], "/pluginrpc.Publisher/Publish", opts...)
	if err != nil {
		return nil, err
	}
	x := &publisherPublishClient{stream}
	return x, nil
}

type Publisher_PublishClient interface {
	Send(*PublishRequest) error
	CloseAndRecv() (*PublishResponse, error)
	grpc.ClientStream
}

type publisherPublishClient struct {
	grpc.ClientStream
}

func (x *publisherPublishClient) Send(m *PublishRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *publisherPublishClient) CloseAndRecv() (*PublishResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PublishResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *publisherClient) Load(ctx context.Context, in *LoadPublisherRequest, opts ...grpc.CallOption) (*LoadPublisherResponse, error) {
	out := new(LoadPublisherResponse)
	err := c.cc.Invoke(ctx, "/pluginrpc.Publisher/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherClient) Unload(ctx context.Context, in *UnloadPublisherRequest, opts ...grpc.CallOption) (*UnloadPublisherResponse, error) {
	out := new(UnloadPublisherResponse)
	err := c.cc.Invoke(ctx, "/pluginrpc.Publisher/Unload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *publisherClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/pluginrpc.Publisher/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PublisherServer is the server API for Publisher service.
type PublisherServer interface {
	Publish(Publisher_PublishServer) error
	Load(context.Context, *LoadPublisherRequest) (*LoadPublisherResponse, error)
	Unload(context.Context, *UnloadPublisherRequest) (*UnloadPublisherResponse, error)
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
}

func RegisterPublisherServer(s *grpc.Server, srv PublisherServer) {
	s.RegisterService(&_Publisher_serviceDesc, srv)
}

func _Publisher_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PublisherServer).Publish(&publisherPublishServer{stream})
}

type Publisher_PublishServer interface {
	SendAndClose(*PublishResponse) error
	Recv() (*PublishRequest, error)
	grpc.ServerStream
}

type publisherPublishServer struct {
	grpc.ServerStream
}

func (x *publisherPublishServer) SendAndClose(m *PublishResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *publisherPublishServer) Recv() (*PublishRequest, error) {
	m := new(PublishRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Publisher_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadPublisherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginrpc.Publisher/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).Load(ctx, req.(*LoadPublisherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Publisher_Unload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadPublisherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).Unload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginrpc.Publisher/Unload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).Unload(ctx, req.(*UnloadPublisherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Publisher_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PublisherServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginrpc.Publisher/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PublisherServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Publisher_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pluginrpc.Publisher",
	HandlerType: (*PublisherServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Load",
			Handler:    _Publisher_Load_Handler,
		},
		{
			MethodName: "Unload",
			Handler:    _Publisher_Unload_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Publisher_Info_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _Publisher_Publish_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_plugin_af2113ffc4edde01) }

var fileDescriptor_plugin_af2113ffc4edde01 = []byte{
	// 905 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0x5f, 0x6f, 0x1b, 0x45,
	0x10, 0xcf, 0x9d, 0x1d, 0x3b, 0x37, 0xe7, 0x26, 0x65, 0x15, 0xea, 0x8b, 0xfb, 0x50, 0x73, 0x0f,
	0xc8, 0x95, 0x8a, 0x29, 0x6e, 0x94, 0x00, 0x6f, 0x24, 0x80, 0x12, 0x51, 0x20, 0xba, 0xb6, 0xf4,
	0x01, 0xa1, 0xd3, 0xda, 0xde, 0x1c, 0x4b, 0xcf, 0xbb, 0xe6, 0x76, 0x6d, 0x14, 0x21, 0xf1, 0x31,
	0xf8, 0x04, 0x7c, 0x09, 0xbe, 0x1d, 0xda, 0x3f, 0x3e, 0xef, 0xf9, 0xd2, 0xb8, 0xa8, 0x6f, 0x3b,
	0x33, 0xbf, 0x99, 0xd9, 0xfd, 0xcd, 0xdc, 0xcc, 0x41, 0x67, 0x9e, 0x2f, 0x32, 0xca, 0x86, 0xf3,
	0x82, 0x4b, 0x8e, 0x02, 0x23, 0x15, 0xf3, 0x49, 0x7c, 0x0f, 0xc2, 0x2b, 0xca, 0xb2, 0x84, 0xfc,
	0xbe, 0x20, 0x42, 0xc6, 0xfb, 0xd0, 0x31, 0xa2, 0x98, 0x73, 0x26, 0x88, 0x32, 0x7f, 0x47, 0xf3,
	0xdc, 0x31, 0x1b, 0xd1, 0x9a, 0x1f, 0xc3, 0xfe, 0x39, 0xcf, 0x73, 0x32, 0x91, 0x16, 0x81, 0xba,
	0xd0, 0x96, 0x58, 0xbc, 0x49, 0xe9, 0x34, 0xf2, 0xfa, 0xde, 0x20, 0x48, 0x5a, 0x4a, 0xbc, 0x9c,
	0xc6, 0x02, 0x0e, 0x4a, 0xa8, 0xf1, 0x46, 0x4f, 0x01, 0x66, 0x44, 0x16, 0x74, 0x92, 0x0a, 0x22,
	0x23, 0xaf, 0xdf, 0x18, 0x84, 0xa3, 0x0f, 0x86, 0xe5, 0xdd, 0x86, 0xdf, 0x6b, 0x63, 0x12, 0x18,
	0xd0, 0x0b, 0x22, 0xd1, 0x10, 0xf6, 0xfe, 0xc0, 0x05, 0xa3, 0x2c, 0x13, 0x91, 0xaf, 0xf1, 0xc8,
	0xc1, 0xbf, 0x36, 0xa6, 0xa4, 0xc4, 0xc4, 0x7f, 0xc2, 0xe1, 0x73, 0x8e, 0xa7, 0x36, 0x31, 0x2f,
	0xb6, 0xdd, 0x12, 0x3d, 0x82, 0xf0, 0x37, 0xc1, 0x59, 0x3a, 0xe1, 0xec, 0x9a, 0x66, 0x91, 0xdf,
	0xf7, 0x06, 0x9d, 0x04, 0x94, 0xea, 0x5c, 0x6b, 0xd0, 0x63, 0xb8, 0x5f, 0xde, 0xd9, 0xc4, 0x14,
	0x51, 0xa3, 0xdf, 0x18, 0x04, 0xc9, 0xc1, 0xea, 0x9a, 0x56, 0x1d, 0x77, 0xe1, 0xc3, 0x8d, 0xe4,
	0x96, 0xb5, 0xcf, 0xe0, 0xc1, 0x2b, 0x96, 0xff, 0x9f, 0x7b, 0xc5, 0x47, 0xd0, 0xad, 0xb9, 0xd8,
	0x68, 0x1f, 0x43, 0x78, 0xc9, 0xae, 0xf9, 0xd6, 0x10, 0xbf, 0x40, 0xc7, 0xe0, 0x2c, 0xfb, 0x5f,
	0x40, 0x27, 0xcd, 0x49, 0x86, 0x27, 0x37, 0x29, 0x65, 0xd7, 0x5c, 0xa3, 0xc3, 0x51, 0xd7, 0xe1,
	0xd3, 0x35, 0x27, 0xf0, 0x5c, 0x0b, 0x2a, 0x04, 0x42, 0xd0, 0xd4, 0x2e, 0x86, 0x1e, 0x7d, 0x8e,
	0x7f, 0x86, 0xfd, 0xab, 0xc5, 0x38, 0xa7, 0xe2, 0xd7, 0xad, 0x24, 0x57, 0xeb, 0xee, 0x6f, 0xaf,
	0x7b, 0xfc, 0x15, 0x1c, 0x94, 0xc1, 0xed, 0xf5, 0xdd, 0x56, 0xf0, 0xde, 0xa1, 0x15, 0xae, 0x4c,
	0x2b, 0xd8, 0x30, 0xe4, 0xfd, 0x5b, 0x61, 0x55, 0x5f, 0x27, 0xe2, 0x66, 0x7d, 0xdf, 0x39, 0xd9,
	0xba, 0xbe, 0xf5, 0x68, 0xff, 0xfa, 0xd0, 0x32, 0x8c, 0xa0, 0x11, 0x04, 0x0c, 0xcf, 0x88, 0x98,
	0xe3, 0x09, 0xb1, 0x8f, 0x3e, 0x74, 0x1e, 0xfd, 0xc3, 0xca, 0x96, 0xac, 0x61, 0xe8, 0x09, 0xec,
	0x2e, 0x71, 0xbe, 0x20, 0xfa, 0x01, 0xe1, 0xe8, 0x41, 0x8d, 0xe7, 0x9f, 0x94, 0x35, 0x31, 0x20,
	0xf4, 0x29, 0x34, 0x25, 0xce, 0x4c, 0x4b, 0x87, 0xa3, 0x87, 0x35, 0xf0, 0xf0, 0x25, 0xce, 0xc4,
	0x37, 0x4c, 0x16, 0x37, 0x89, 0x06, 0xa2, 0x4f, 0x20, 0x90, 0x74, 0x46, 0x84, 0xc4, 0xb3, 0x79,
	0xd4, 0xd4, 0x29, 0x0e, 0x1c, 0xaf, 0x97, 0x74, 0x46, 0x92, 0x35, 0x02, 0xf5, 0x21, 0x9c, 0x12,
	0x31, 0x29, 0xe8, 0x5c, 0x52, 0xce, 0xa2, 0x5d, 0x4d, 0x82, 0xab, 0x52, 0xbd, 0xb5, 0x60, 0x54,
	0x46, 0x2d, 0x6d, 0xd2, 0xe7, 0xde, 0x29, 0x04, 0x65, 0x5e, 0x74, 0x1f, 0x1a, 0x6f, 0xc8, 0x8d,
	0xe5, 0x4f, 0x1d, 0xd1, 0xa1, 0xfb, 0xc4, 0xc0, 0x3e, 0xe5, 0x4b, 0xff, 0x73, 0x2f, 0x7e, 0x0d,
	0x41, 0x49, 0x8a, 0x8a, 0xac, 0x68, 0xb1, 0x9e, 0xfa, 0x7c, 0xbb, 0xeb, 0xe6, 0x2d, 0x1b, 0xb5,
	0x5b, 0xc6, 0x7f, 0xfb, 0x10, 0x3a, 0xf4, 0xa1, 0x23, 0x68, 0x2f, 0xd3, 0xeb, 0x9c, 0x63, 0xa9,
	0xc3, 0xfb, 0x17, 0x3b, 0x49, 0x6b, 0xf9, 0xad, 0x92, 0xd1, 0x43, 0xd8, 0x5b, 0xa6, 0x53, 0xbe,
	0x18, 0xe7, 0x26, 0x8b, 0x77, 0xb1, 0x93, 0xb4, 0x97, 0x5f, 0x6b, 0x85, 0xf1, 0xa3, 0x4c, 0x3e,
	0x1b, 0xe9, 0x2c, 0xbb, 0xda, 0xef, 0x52, 0xc9, 0xa5, 0xe9, 0xe4, 0x58, 0xf3, 0xda, 0x58, 0x99,
	0x4e, 0x8e, 0x4d, 0xc8, 0x85, 0x71, 0x53, 0x14, 0xde, 0xd3, 0x21, 0x5f, 0x69, 0xc5, 0xda, 0x78,
	0x72, 0xac, 0x49, 0x6c, 0x96, 0xc6, 0x93, 0x63, 0xd4, 0x85, 0xd6, 0x32, 0x1d, 0x73, 0x9e, 0x47,
	0xed, 0xbe, 0x37, 0xd8, 0xbb, 0xd8, 0x49, 0x76, 0x97, 0x67, 0x9c, 0xe7, 0x26, 0xdb, 0xf8, 0x46,
	0x12, 0x11, 0xed, 0xa9, 0x4e, 0xd7, 0xd9, 0xce, 0x94, 0x6c, 0x02, 0x0a, 0x59, 0x50, 0x96, 0x45,
	0x81, 0xa2, 0x42, 0x07, 0x7c, 0xa1, 0x15, 0x67, 0xfb, 0xd0, 0x99, 0x62, 0x89, 0xd3, 0x25, 0x2e,
	0x28, 0x66, 0x32, 0x7e, 0x02, 0x4d, 0x55, 0x73, 0x55, 0x25, 0x41, 0x26, 0x9a, 0x8c, 0x46, 0xa2,
	0x8e, 0x9a, 0x7e, 0xa5, 0xf2, 0xb5, 0x4a, 0x9f, 0xe3, 0x04, 0xda, 0xf6, 0x4b, 0x45, 0x11, 0xb4,
	0x67, 0x44, 0x08, 0x9c, 0xad, 0x0a, 0xb4, 0x12, 0xab, 0x2d, 0xe6, 0x6f, 0x6b, 0x31, 0xb5, 0xa3,
	0xdc, 0xc1, 0x35, 0xfa, 0x0b, 0xe0, 0x9c, 0x33, 0x59, 0xa8, 0xc1, 0x59, 0xa0, 0x53, 0x68, 0xaa,
	0x05, 0x87, 0xdc, 0xef, 0xc0, 0x59, 0x80, 0xbd, 0x6e, 0x4d, 0x6f, 0xe7, 0xcd, 0x29, 0x34, 0xd5,
	0xea, 0xab, 0x38, 0x3a, 0xab, 0xb1, 0xe2, 0xe8, 0xee, 0xc8, 0xd1, 0x3f, 0x3e, 0x04, 0xe5, 0xd4,
	0x46, 0x67, 0xd0, 0xb6, 0x02, 0x3a, 0x72, 0x3c, 0xaa, 0x5b, 0xb4, 0xd7, 0xbb, 0xcd, 0x64, 0xe2,
	0x3d, 0xf5, 0xd0, 0x25, 0x34, 0xd5, 0xe0, 0x41, 0x8f, 0x1c, 0xd4, 0x6d, 0x6b, 0xae, 0xd7, 0x7f,
	0x3b, 0xc0, 0xbe, 0xea, 0x47, 0x68, 0x99, 0xb9, 0x83, 0x3e, 0x72, 0xb0, 0xb7, 0x6f, 0xa7, 0x5e,
	0x7c, 0x17, 0x64, 0x4d, 0x93, 0x5e, 0x11, 0x2e, 0x4d, 0xce, 0x7a, 0xaa, 0xd0, 0xe4, 0xae, 0x23,
	0x4d, 0x53, 0x39, 0xfc, 0x14, 0x4d, 0x56, 0xa8, 0xd0, 0x54, 0xdd, 0x30, 0x15, 0x9a, 0x36, 0xf6,
	0xc3, 0xe0, 0xed, 0x34, 0x6d, 0x4e, 0xe5, 0x1a, 0x4d, 0xb5, 0x19, 0x7c, 0x27, 0x4d, 0xb5, 0x70,
	0xf1, 0x5d, 0x90, 0xf7, 0xa4, 0x69, 0xdc, 0xd2, 0x7f, 0x70, 0xcf, 0xfe, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0x62, 0x2c, 0xea, 0xef, 0xd1, 0x09, 0x00, 0x00,
}
