/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package github.com/librato/snap-plugin-lib-go/v2/plugin-lib */


#line 1 "cgo-builtin-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

typedef struct { const char *p; ptrdiff_t n; } _GoString_;

#endif

/* Start of preamble from import "C" comments.  */


#line 13 "main.go"

#include <stdlib.h>

// c types for callbacks
typedef void (callback_t)(char *);  // used for Collect, Load and Unload
typedef void (define_callback_t)(); // used for DefineCallback

// called from Go code
static inline void call_c_callback(callback_t callback, char * ctxId) { callback(ctxId); }
static inline void call_c_define_callback(define_callback_t callback) { callback(); }

// some helpers to manage C/Go memory/access interactions
typedef struct {
    char * key;
    char * value;
} tag_t;

static inline char * tag_key(tag_t * tags, int index) { return tags[index].key; }
static inline char * tag_value(tag_t * tags, int index) { return tags[index].value; }

typedef struct {
    char * msg;
} error_t;

static inline error_t * alloc_error_msg(char * msg) {
    error_t * errMsg = malloc(sizeof(error_t));
    errMsg->msg = msg;
    return errMsg;
}


#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

typedef _GoString_ GoString;
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


extern error_t* ctx_add_metric(char* p0, char* p1, GoInt p2);

extern error_t* ctx_add_metric_with_tags(char* p0, char* p1, GoInt p2, tag_t* p3, GoInt p4);

extern error_t* ctx_apply_tags_by_path(char* p0, char* p1, tag_t* p2, GoInt p3);

extern error_t* ctx_apply_tags_by_regexp(char* p0, char* p1, tag_t* p2, GoInt p3);

extern GoInt ctx_should_process(char* p0, char* p1);

extern char* ctx_config(char* p0, char* p1);

extern char* ctx_raw_config(char* p0);

extern void ctx_store(char* p0, char* p1, void* p2);

extern void* ctx_load(char* p0, char* p1);

extern void define_metric(char* p0, char* p1, GoInt p2, char* p3);

extern void define_group(char* p0, char* p1);

extern error_t* define_example_config(char* p0);

extern void define_tasks_per_instance_limit(GoInt p0);

extern void define_instances_limit(GoInt p0);

extern void start_collector(callback_t* p0, callback_t* p1, callback_t* p2, define_callback_t* p3, char* p4, char* p5);

#ifdef __cplusplus
}
#endif
