// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package pluginrpc

import (
	"fmt"
	"math"

	"github.com/golang/protobuf/proto"
	"golang.org/x/net/context"
	"google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingRequest) Reset()         { *m = PingRequest{} }
func (m *PingRequest) String() string { return proto.CompactTextString(m) }
func (*PingRequest) ProtoMessage()    {}
func (*PingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{0}
}
func (m *PingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingRequest.Unmarshal(m, b)
}
func (m *PingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingRequest.Marshal(b, m, deterministic)
}
func (dst *PingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingRequest.Merge(dst, src)
}
func (m *PingRequest) XXX_Size() int {
	return xxx_messageInfo_PingRequest.Size(m)
}
func (m *PingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PingRequest proto.InternalMessageInfo

type PingResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PingResponse) Reset()         { *m = PingResponse{} }
func (m *PingResponse) String() string { return proto.CompactTextString(m) }
func (*PingResponse) ProtoMessage()    {}
func (*PingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{1}
}
func (m *PingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PingResponse.Unmarshal(m, b)
}
func (m *PingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PingResponse.Marshal(b, m, deterministic)
}
func (dst *PingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PingResponse.Merge(dst, src)
}
func (m *PingResponse) XXX_Size() int {
	return xxx_messageInfo_PingResponse.Size(m)
}
func (m *PingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PingResponse proto.InternalMessageInfo

type KillRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillRequest) Reset()         { *m = KillRequest{} }
func (m *KillRequest) String() string { return proto.CompactTextString(m) }
func (*KillRequest) ProtoMessage()    {}
func (*KillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{2}
}
func (m *KillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillRequest.Unmarshal(m, b)
}
func (m *KillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillRequest.Marshal(b, m, deterministic)
}
func (dst *KillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillRequest.Merge(dst, src)
}
func (m *KillRequest) XXX_Size() int {
	return xxx_messageInfo_KillRequest.Size(m)
}
func (m *KillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KillRequest proto.InternalMessageInfo

type KillResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KillResponse) Reset()         { *m = KillResponse{} }
func (m *KillResponse) String() string { return proto.CompactTextString(m) }
func (*KillResponse) ProtoMessage()    {}
func (*KillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{3}
}
func (m *KillResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KillResponse.Unmarshal(m, b)
}
func (m *KillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KillResponse.Marshal(b, m, deterministic)
}
func (dst *KillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KillResponse.Merge(dst, src)
}
func (m *KillResponse) XXX_Size() int {
	return xxx_messageInfo_KillResponse.Size(m)
}
func (m *KillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KillResponse proto.InternalMessageInfo

type CollectRequest struct {
	TaskId               int32    `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CollectRequest) Reset()         { *m = CollectRequest{} }
func (m *CollectRequest) String() string { return proto.CompactTextString(m) }
func (*CollectRequest) ProtoMessage()    {}
func (*CollectRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{4}
}
func (m *CollectRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectRequest.Unmarshal(m, b)
}
func (m *CollectRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectRequest.Marshal(b, m, deterministic)
}
func (dst *CollectRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectRequest.Merge(dst, src)
}
func (m *CollectRequest) XXX_Size() int {
	return xxx_messageInfo_CollectRequest.Size(m)
}
func (m *CollectRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CollectRequest proto.InternalMessageInfo

func (m *CollectRequest) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type CollectResponse struct {
	MetricSet            []*Metric `protobuf:"bytes,1,rep,name=metric_set,json=metricSet,proto3" json:"metric_set,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CollectResponse) Reset()         { *m = CollectResponse{} }
func (m *CollectResponse) String() string { return proto.CompactTextString(m) }
func (*CollectResponse) ProtoMessage()    {}
func (*CollectResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{5}
}
func (m *CollectResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CollectResponse.Unmarshal(m, b)
}
func (m *CollectResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CollectResponse.Marshal(b, m, deterministic)
}
func (dst *CollectResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CollectResponse.Merge(dst, src)
}
func (m *CollectResponse) XXX_Size() int {
	return xxx_messageInfo_CollectResponse.Size(m)
}
func (m *CollectResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CollectResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CollectResponse proto.InternalMessageInfo

func (m *CollectResponse) GetMetricSet() []*Metric {
	if m != nil {
		return m.MetricSet
	}
	return nil
}

type LoadRequest struct {
	TaskId               int32    `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	JsonConfig           []byte   `protobuf:"bytes,2,opt,name=json_config,json=jsonConfig,proto3" json:"json_config,omitempty"`
	MetricSelectors      []string `protobuf:"bytes,3,rep,name=metric_selectors,json=metricSelectors,proto3" json:"metric_selectors,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadRequest) Reset()         { *m = LoadRequest{} }
func (m *LoadRequest) String() string { return proto.CompactTextString(m) }
func (*LoadRequest) ProtoMessage()    {}
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{6}
}
func (m *LoadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadRequest.Unmarshal(m, b)
}
func (m *LoadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadRequest.Marshal(b, m, deterministic)
}
func (dst *LoadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadRequest.Merge(dst, src)
}
func (m *LoadRequest) XXX_Size() int {
	return xxx_messageInfo_LoadRequest.Size(m)
}
func (m *LoadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadRequest proto.InternalMessageInfo

func (m *LoadRequest) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *LoadRequest) GetJsonConfig() []byte {
	if m != nil {
		return m.JsonConfig
	}
	return nil
}

func (m *LoadRequest) GetMetricSelectors() []string {
	if m != nil {
		return m.MetricSelectors
	}
	return nil
}

type LoadResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadResponse) Reset()         { *m = LoadResponse{} }
func (m *LoadResponse) String() string { return proto.CompactTextString(m) }
func (*LoadResponse) ProtoMessage()    {}
func (*LoadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{7}
}
func (m *LoadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadResponse.Unmarshal(m, b)
}
func (m *LoadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadResponse.Marshal(b, m, deterministic)
}
func (dst *LoadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadResponse.Merge(dst, src)
}
func (m *LoadResponse) XXX_Size() int {
	return xxx_messageInfo_LoadResponse.Size(m)
}
func (m *LoadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoadResponse proto.InternalMessageInfo

type UnloadRequest struct {
	TaskId               int32    `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnloadRequest) Reset()         { *m = UnloadRequest{} }
func (m *UnloadRequest) String() string { return proto.CompactTextString(m) }
func (*UnloadRequest) ProtoMessage()    {}
func (*UnloadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{8}
}
func (m *UnloadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnloadRequest.Unmarshal(m, b)
}
func (m *UnloadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnloadRequest.Marshal(b, m, deterministic)
}
func (dst *UnloadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnloadRequest.Merge(dst, src)
}
func (m *UnloadRequest) XXX_Size() int {
	return xxx_messageInfo_UnloadRequest.Size(m)
}
func (m *UnloadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnloadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnloadRequest proto.InternalMessageInfo

func (m *UnloadRequest) GetTaskId() int32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type UnloadResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnloadResponse) Reset()         { *m = UnloadResponse{} }
func (m *UnloadResponse) String() string { return proto.CompactTextString(m) }
func (*UnloadResponse) ProtoMessage()    {}
func (*UnloadResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{9}
}
func (m *UnloadResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnloadResponse.Unmarshal(m, b)
}
func (m *UnloadResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnloadResponse.Marshal(b, m, deterministic)
}
func (dst *UnloadResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnloadResponse.Merge(dst, src)
}
func (m *UnloadResponse) XXX_Size() int {
	return xxx_messageInfo_UnloadResponse.Size(m)
}
func (m *UnloadResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UnloadResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UnloadResponse proto.InternalMessageInfo

type InfoRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoRequest) Reset()         { *m = InfoRequest{} }
func (m *InfoRequest) String() string { return proto.CompactTextString(m) }
func (*InfoRequest) ProtoMessage()    {}
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{10}
}
func (m *InfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoRequest.Unmarshal(m, b)
}
func (m *InfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoRequest.Marshal(b, m, deterministic)
}
func (dst *InfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoRequest.Merge(dst, src)
}
func (m *InfoRequest) XXX_Size() int {
	return xxx_messageInfo_InfoRequest.Size(m)
}
func (m *InfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InfoRequest proto.InternalMessageInfo

type InfoResponse struct {
	Info                 *Info    `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InfoResponse) Reset()         { *m = InfoResponse{} }
func (m *InfoResponse) String() string { return proto.CompactTextString(m) }
func (*InfoResponse) ProtoMessage()    {}
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{11}
}
func (m *InfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InfoResponse.Unmarshal(m, b)
}
func (m *InfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InfoResponse.Marshal(b, m, deterministic)
}
func (dst *InfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InfoResponse.Merge(dst, src)
}
func (m *InfoResponse) XXX_Size() int {
	return xxx_messageInfo_InfoResponse.Size(m)
}
func (m *InfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_InfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_InfoResponse proto.InternalMessageInfo

func (m *InfoResponse) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

type Metric struct {
	Namespace            []*Namespace      `protobuf:"bytes,1,rep,name=namespace,proto3" json:"namespace,omitempty"`
	Value                *MetricValue      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Timestamp            *Time             `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Description          string            `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	Unit                 string            `protobuf:"bytes,6,opt,name=unit,proto3" json:"unit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{12}
}
func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (dst *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(dst, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetNamespace() []*Namespace {
	if m != nil {
		return m.Namespace
	}
	return nil
}

func (m *Metric) GetValue() *MetricValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Metric) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Metric) GetTimestamp() *Time {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *Metric) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Metric) GetUnit() string {
	if m != nil {
		return m.Unit
	}
	return ""
}

type Namespace struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Namespace) Reset()         { *m = Namespace{} }
func (m *Namespace) String() string { return proto.CompactTextString(m) }
func (*Namespace) ProtoMessage()    {}
func (*Namespace) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{13}
}
func (m *Namespace) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Namespace.Unmarshal(m, b)
}
func (m *Namespace) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Namespace.Marshal(b, m, deterministic)
}
func (dst *Namespace) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Namespace.Merge(dst, src)
}
func (m *Namespace) XXX_Size() int {
	return xxx_messageInfo_Namespace.Size(m)
}
func (m *Namespace) XXX_DiscardUnknown() {
	xxx_messageInfo_Namespace.DiscardUnknown(m)
}

var xxx_messageInfo_Namespace proto.InternalMessageInfo

func (m *Namespace) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Namespace) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *Namespace) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type MetricValue struct {
	// Types that are valid to be assigned to DataVariant:
	//	*MetricValue_VFloat
	//	*MetricValue_VDouble
	//	*MetricValue_VInt32
	//	*MetricValue_VInt64
	//	*MetricValue_VUint32
	//	*MetricValue_VUint64
	//	*MetricValue_VBool
	//	*MetricValue_VBytes
	//	*MetricValue_VString
	DataVariant          isMetricValue_DataVariant `protobuf_oneof:"data_variant"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *MetricValue) Reset()         { *m = MetricValue{} }
func (m *MetricValue) String() string { return proto.CompactTextString(m) }
func (*MetricValue) ProtoMessage()    {}
func (*MetricValue) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{14}
}
func (m *MetricValue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricValue.Unmarshal(m, b)
}
func (m *MetricValue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricValue.Marshal(b, m, deterministic)
}
func (dst *MetricValue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricValue.Merge(dst, src)
}
func (m *MetricValue) XXX_Size() int {
	return xxx_messageInfo_MetricValue.Size(m)
}
func (m *MetricValue) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricValue.DiscardUnknown(m)
}

var xxx_messageInfo_MetricValue proto.InternalMessageInfo

type isMetricValue_DataVariant interface {
	isMetricValue_DataVariant()
}

type MetricValue_VFloat struct {
	VFloat float32 `protobuf:"fixed32,1,opt,name=v_float,json=vFloat,proto3,oneof"`
}

type MetricValue_VDouble struct {
	VDouble float64 `protobuf:"fixed64,2,opt,name=v_double,json=vDouble,proto3,oneof"`
}

type MetricValue_VInt32 struct {
	VInt32 int32 `protobuf:"varint,3,opt,name=v_int32,json=vInt32,proto3,oneof"`
}

type MetricValue_VInt64 struct {
	VInt64 int64 `protobuf:"varint,4,opt,name=v_int64,json=vInt64,proto3,oneof"`
}

type MetricValue_VUint32 struct {
	VUint32 uint32 `protobuf:"varint,5,opt,name=v_uint32,json=vUint32,proto3,oneof"`
}

type MetricValue_VUint64 struct {
	VUint64 uint64 `protobuf:"varint,6,opt,name=v_uint64,json=vUint64,proto3,oneof"`
}

type MetricValue_VBool struct {
	VBool bool `protobuf:"varint,7,opt,name=v_bool,json=vBool,proto3,oneof"`
}

type MetricValue_VBytes struct {
	VBytes []byte `protobuf:"bytes,8,opt,name=v_bytes,json=vBytes,proto3,oneof"`
}

type MetricValue_VString struct {
	VString string `protobuf:"bytes,9,opt,name=v_string,json=vString,proto3,oneof"`
}

func (*MetricValue_VFloat) isMetricValue_DataVariant() {}

func (*MetricValue_VDouble) isMetricValue_DataVariant() {}

func (*MetricValue_VInt32) isMetricValue_DataVariant() {}

func (*MetricValue_VInt64) isMetricValue_DataVariant() {}

func (*MetricValue_VUint32) isMetricValue_DataVariant() {}

func (*MetricValue_VUint64) isMetricValue_DataVariant() {}

func (*MetricValue_VBool) isMetricValue_DataVariant() {}

func (*MetricValue_VBytes) isMetricValue_DataVariant() {}

func (*MetricValue_VString) isMetricValue_DataVariant() {}

func (m *MetricValue) GetDataVariant() isMetricValue_DataVariant {
	if m != nil {
		return m.DataVariant
	}
	return nil
}

func (m *MetricValue) GetVFloat() float32 {
	if x, ok := m.GetDataVariant().(*MetricValue_VFloat); ok {
		return x.VFloat
	}
	return 0
}

func (m *MetricValue) GetVDouble() float64 {
	if x, ok := m.GetDataVariant().(*MetricValue_VDouble); ok {
		return x.VDouble
	}
	return 0
}

func (m *MetricValue) GetVInt32() int32 {
	if x, ok := m.GetDataVariant().(*MetricValue_VInt32); ok {
		return x.VInt32
	}
	return 0
}

func (m *MetricValue) GetVInt64() int64 {
	if x, ok := m.GetDataVariant().(*MetricValue_VInt64); ok {
		return x.VInt64
	}
	return 0
}

func (m *MetricValue) GetVUint32() uint32 {
	if x, ok := m.GetDataVariant().(*MetricValue_VUint32); ok {
		return x.VUint32
	}
	return 0
}

func (m *MetricValue) GetVUint64() uint64 {
	if x, ok := m.GetDataVariant().(*MetricValue_VUint64); ok {
		return x.VUint64
	}
	return 0
}

func (m *MetricValue) GetVBool() bool {
	if x, ok := m.GetDataVariant().(*MetricValue_VBool); ok {
		return x.VBool
	}
	return false
}

func (m *MetricValue) GetVBytes() []byte {
	if x, ok := m.GetDataVariant().(*MetricValue_VBytes); ok {
		return x.VBytes
	}
	return nil
}

func (m *MetricValue) GetVString() string {
	if x, ok := m.GetDataVariant().(*MetricValue_VString); ok {
		return x.VString
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*MetricValue) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _MetricValue_OneofMarshaler, _MetricValue_OneofUnmarshaler, _MetricValue_OneofSizer, []interface{}{
		(*MetricValue_VFloat)(nil),
		(*MetricValue_VDouble)(nil),
		(*MetricValue_VInt32)(nil),
		(*MetricValue_VInt64)(nil),
		(*MetricValue_VUint32)(nil),
		(*MetricValue_VUint64)(nil),
		(*MetricValue_VBool)(nil),
		(*MetricValue_VBytes)(nil),
		(*MetricValue_VString)(nil),
	}
}

func _MetricValue_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*MetricValue)
	// data_variant
	switch x := m.DataVariant.(type) {
	case *MetricValue_VFloat:
		b.EncodeVarint(1<<3 | proto.WireFixed32)
		b.EncodeFixed32(uint64(math.Float32bits(x.VFloat)))
	case *MetricValue_VDouble:
		b.EncodeVarint(2<<3 | proto.WireFixed64)
		b.EncodeFixed64(math.Float64bits(x.VDouble))
	case *MetricValue_VInt32:
		b.EncodeVarint(3<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.VInt32))
	case *MetricValue_VInt64:
		b.EncodeVarint(4<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.VInt64))
	case *MetricValue_VUint32:
		b.EncodeVarint(5<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.VUint32))
	case *MetricValue_VUint64:
		b.EncodeVarint(6<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.VUint64))
	case *MetricValue_VBool:
		t := uint64(0)
		if x.VBool {
			t = 1
		}
		b.EncodeVarint(7<<3 | proto.WireVarint)
		b.EncodeVarint(t)
	case *MetricValue_VBytes:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		b.EncodeRawBytes(x.VBytes)
	case *MetricValue_VString:
		b.EncodeVarint(9<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.VString)
	case nil:
	default:
		return fmt.Errorf("MetricValue.DataVariant has unexpected type %T", x)
	}
	return nil
}

func _MetricValue_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*MetricValue)
	switch tag {
	case 1: // data_variant.v_float
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.DataVariant = &MetricValue_VFloat{math.Float32frombits(uint32(x))}
		return true, err
	case 2: // data_variant.v_double
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.DataVariant = &MetricValue_VDouble{math.Float64frombits(x)}
		return true, err
	case 3: // data_variant.v_int32
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.DataVariant = &MetricValue_VInt32{int32(x)}
		return true, err
	case 4: // data_variant.v_int64
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.DataVariant = &MetricValue_VInt64{int64(x)}
		return true, err
	case 5: // data_variant.v_uint32
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.DataVariant = &MetricValue_VUint32{uint32(x)}
		return true, err
	case 6: // data_variant.v_uint64
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.DataVariant = &MetricValue_VUint64{x}
		return true, err
	case 7: // data_variant.v_bool
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.DataVariant = &MetricValue_VBool{x != 0}
		return true, err
	case 8: // data_variant.v_bytes
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.DataVariant = &MetricValue_VBytes{x}
		return true, err
	case 9: // data_variant.v_string
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.DataVariant = &MetricValue_VString{x}
		return true, err
	default:
		return false, nil
	}
}

func _MetricValue_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*MetricValue)
	// data_variant
	switch x := m.DataVariant.(type) {
	case *MetricValue_VFloat:
		n += 1 // tag and wire
		n += 4
	case *MetricValue_VDouble:
		n += 1 // tag and wire
		n += 8
	case *MetricValue_VInt32:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.VInt32))
	case *MetricValue_VInt64:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.VInt64))
	case *MetricValue_VUint32:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.VUint32))
	case *MetricValue_VUint64:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.VUint64))
	case *MetricValue_VBool:
		n += 1 // tag and wire
		n += 1
	case *MetricValue_VBytes:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.VBytes)))
		n += len(x.VBytes)
	case *MetricValue_VString:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.VString)))
		n += len(x.VString)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Time struct {
	Sec                  int64    `protobuf:"varint,1,opt,name=sec,proto3" json:"sec,omitempty"`
	Nsec                 int64    `protobuf:"varint,2,opt,name=nsec,proto3" json:"nsec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Time) Reset()         { *m = Time{} }
func (m *Time) String() string { return proto.CompactTextString(m) }
func (*Time) ProtoMessage()    {}
func (*Time) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{15}
}
func (m *Time) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Time.Unmarshal(m, b)
}
func (m *Time) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Time.Marshal(b, m, deterministic)
}
func (dst *Time) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Time.Merge(dst, src)
}
func (m *Time) XXX_Size() int {
	return xxx_messageInfo_Time.Size(m)
}
func (m *Time) XXX_DiscardUnknown() {
	xxx_messageInfo_Time.DiscardUnknown(m)
}

var xxx_messageInfo_Time proto.InternalMessageInfo

func (m *Time) GetSec() int64 {
	if m != nil {
		return m.Sec
	}
	return 0
}

func (m *Time) GetNsec() int64 {
	if m != nil {
		return m.Nsec
	}
	return 0
}

type Info struct {
	PluginInfo           *PluginInfo             `protobuf:"bytes,1,opt,name=pluginInfo,proto3" json:"pluginInfo,omitempty"`
	TaskSummary          *TaskSummary            `protobuf:"bytes,2,opt,name=taskSummary,proto3" json:"taskSummary,omitempty"`
	TaskDetails          map[uint64]*TaskDetails `protobuf:"bytes,3,rep,name=taskDetails,proto3" json:"taskDetails,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *Info) Reset()         { *m = Info{} }
func (m *Info) String() string { return proto.CompactTextString(m) }
func (*Info) ProtoMessage()    {}
func (*Info) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{16}
}
func (m *Info) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Info.Unmarshal(m, b)
}
func (m *Info) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Info.Marshal(b, m, deterministic)
}
func (dst *Info) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Info.Merge(dst, src)
}
func (m *Info) XXX_Size() int {
	return xxx_messageInfo_Info.Size(m)
}
func (m *Info) XXX_DiscardUnknown() {
	xxx_messageInfo_Info.DiscardUnknown(m)
}

var xxx_messageInfo_Info proto.InternalMessageInfo

func (m *Info) GetPluginInfo() *PluginInfo {
	if m != nil {
		return m.PluginInfo
	}
	return nil
}

func (m *Info) GetTaskSummary() *TaskSummary {
	if m != nil {
		return m.TaskSummary
	}
	return nil
}

func (m *Info) GetTaskDetails() map[uint64]*TaskDetails {
	if m != nil {
		return m.TaskDetails
	}
	return nil
}

type PluginInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	CmdLineOptions       string   `protobuf:"bytes,3,opt,name=cmdLineOptions,proto3" json:"cmdLineOptions,omitempty"`
	Options              *Options `protobuf:"bytes,4,opt,name=options,proto3" json:"options,omitempty"`
	Started              *Time    `protobuf:"bytes,5,opt,name=started,proto3" json:"started,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PluginInfo) Reset()         { *m = PluginInfo{} }
func (m *PluginInfo) String() string { return proto.CompactTextString(m) }
func (*PluginInfo) ProtoMessage()    {}
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{17}
}
func (m *PluginInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PluginInfo.Unmarshal(m, b)
}
func (m *PluginInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PluginInfo.Marshal(b, m, deterministic)
}
func (dst *PluginInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PluginInfo.Merge(dst, src)
}
func (m *PluginInfo) XXX_Size() int {
	return xxx_messageInfo_PluginInfo.Size(m)
}
func (m *PluginInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PluginInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PluginInfo proto.InternalMessageInfo

func (m *PluginInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *PluginInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PluginInfo) GetCmdLineOptions() string {
	if m != nil {
		return m.CmdLineOptions
	}
	return ""
}

func (m *PluginInfo) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *PluginInfo) GetStarted() *Time {
	if m != nil {
		return m.Started
	}
	return nil
}

type Options struct {
	PluginIP             string   `protobuf:"bytes,1,opt,name=pluginIP,proto3" json:"pluginIP,omitempty"`
	GrpcPort             uint32   `protobuf:"varint,2,opt,name=grpcPort,proto3" json:"grpcPort,omitempty"`
	PprofPort            uint32   `protobuf:"varint,3,opt,name=pprofPort,proto3" json:"pprofPort,omitempty"`
	StatsPort            uint32   `protobuf:"varint,4,opt,name=statsPort,proto3" json:"statsPort,omitempty"`
	GrpcPingTimeout      int64    `protobuf:"varint,5,opt,name=grpcPingTimeout,proto3" json:"grpcPingTimeout,omitempty"`
	GrpcPingMaxMissed    uint64   `protobuf:"varint,6,opt,name=grpcPingMaxMissed,proto3" json:"grpcPingMaxMissed,omitempty"`
	LogLevel             string   `protobuf:"bytes,7,opt,name=logLevel,proto3" json:"logLevel,omitempty"`
	EnablePprofServer    bool     `protobuf:"varint,8,opt,name=enablePprofServer,proto3" json:"enablePprofServer,omitempty"`
	EnableStats          bool     `protobuf:"varint,9,opt,name=enableStats,proto3" json:"enableStats,omitempty"`
	EnableStatsServer    bool     `protobuf:"varint,10,opt,name=enableStatsServer,proto3" json:"enableStatsServer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{18}
}
func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (dst *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(dst, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetPluginIP() string {
	if m != nil {
		return m.PluginIP
	}
	return ""
}

func (m *Options) GetGrpcPort() uint32 {
	if m != nil {
		return m.GrpcPort
	}
	return 0
}

func (m *Options) GetPprofPort() uint32 {
	if m != nil {
		return m.PprofPort
	}
	return 0
}

func (m *Options) GetStatsPort() uint32 {
	if m != nil {
		return m.StatsPort
	}
	return 0
}

func (m *Options) GetGrpcPingTimeout() int64 {
	if m != nil {
		return m.GrpcPingTimeout
	}
	return 0
}

func (m *Options) GetGrpcPingMaxMissed() uint64 {
	if m != nil {
		return m.GrpcPingMaxMissed
	}
	return 0
}

func (m *Options) GetLogLevel() string {
	if m != nil {
		return m.LogLevel
	}
	return ""
}

func (m *Options) GetEnablePprofServer() bool {
	if m != nil {
		return m.EnablePprofServer
	}
	return false
}

func (m *Options) GetEnableStats() bool {
	if m != nil {
		return m.EnableStats
	}
	return false
}

func (m *Options) GetEnableStatsServer() bool {
	if m != nil {
		return m.EnableStatsServer
	}
	return false
}

type TaskSummary struct {
	Counters             *TaskSummaryCounters `protobuf:"bytes,1,opt,name=counters,proto3" json:"counters,omitempty"`
	ProcessingTimes      *ProcessingTimes     `protobuf:"bytes,2,opt,name=processingTimes,proto3" json:"processingTimes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *TaskSummary) Reset()         { *m = TaskSummary{} }
func (m *TaskSummary) String() string { return proto.CompactTextString(m) }
func (*TaskSummary) ProtoMessage()    {}
func (*TaskSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{19}
}
func (m *TaskSummary) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskSummary.Unmarshal(m, b)
}
func (m *TaskSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskSummary.Marshal(b, m, deterministic)
}
func (dst *TaskSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskSummary.Merge(dst, src)
}
func (m *TaskSummary) XXX_Size() int {
	return xxx_messageInfo_TaskSummary.Size(m)
}
func (m *TaskSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskSummary.DiscardUnknown(m)
}

var xxx_messageInfo_TaskSummary proto.InternalMessageInfo

func (m *TaskSummary) GetCounters() *TaskSummaryCounters {
	if m != nil {
		return m.Counters
	}
	return nil
}

func (m *TaskSummary) GetProcessingTimes() *ProcessingTimes {
	if m != nil {
		return m.ProcessingTimes
	}
	return nil
}

type TaskDetails struct {
	Configuration        string              `protobuf:"bytes,1,opt,name=configuration,proto3" json:"configuration,omitempty"`
	Filters              []string            `protobuf:"bytes,2,rep,name=filters,proto3" json:"filters,omitempty"`
	Counters             *TaskDetailCounters `protobuf:"bytes,3,opt,name=counters,proto3" json:"counters,omitempty"`
	Loaded               *Time               `protobuf:"bytes,4,opt,name=loaded,proto3" json:"loaded,omitempty"`
	ProcessingTimes      *ProcessingTimes    `protobuf:"bytes,5,opt,name=processingTimes,proto3" json:"processingTimes,omitempty"`
	LastMeasurement      *LastMeasurement    `protobuf:"bytes,6,opt,name=lastMeasurement,proto3" json:"lastMeasurement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *TaskDetails) Reset()         { *m = TaskDetails{} }
func (m *TaskDetails) String() string { return proto.CompactTextString(m) }
func (*TaskDetails) ProtoMessage()    {}
func (*TaskDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{20}
}
func (m *TaskDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDetails.Unmarshal(m, b)
}
func (m *TaskDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDetails.Marshal(b, m, deterministic)
}
func (dst *TaskDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDetails.Merge(dst, src)
}
func (m *TaskDetails) XXX_Size() int {
	return xxx_messageInfo_TaskDetails.Size(m)
}
func (m *TaskDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDetails.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDetails proto.InternalMessageInfo

func (m *TaskDetails) GetConfiguration() string {
	if m != nil {
		return m.Configuration
	}
	return ""
}

func (m *TaskDetails) GetFilters() []string {
	if m != nil {
		return m.Filters
	}
	return nil
}

func (m *TaskDetails) GetCounters() *TaskDetailCounters {
	if m != nil {
		return m.Counters
	}
	return nil
}

func (m *TaskDetails) GetLoaded() *Time {
	if m != nil {
		return m.Loaded
	}
	return nil
}

func (m *TaskDetails) GetProcessingTimes() *ProcessingTimes {
	if m != nil {
		return m.ProcessingTimes
	}
	return nil
}

func (m *TaskDetails) GetLastMeasurement() *LastMeasurement {
	if m != nil {
		return m.LastMeasurement
	}
	return nil
}

type TaskSummaryCounters struct {
	CurrentlyActiveTasks uint64   `protobuf:"varint,1,opt,name=currentlyActiveTasks,proto3" json:"currentlyActiveTasks,omitempty"`
	TotalActiveTasks     uint64   `protobuf:"varint,2,opt,name=totalActiveTasks,proto3" json:"totalActiveTasks,omitempty"`
	TotalCollectRequests uint64   `protobuf:"varint,3,opt,name=totalCollectRequests,proto3" json:"totalCollectRequests,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskSummaryCounters) Reset()         { *m = TaskSummaryCounters{} }
func (m *TaskSummaryCounters) String() string { return proto.CompactTextString(m) }
func (*TaskSummaryCounters) ProtoMessage()    {}
func (*TaskSummaryCounters) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{21}
}
func (m *TaskSummaryCounters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskSummaryCounters.Unmarshal(m, b)
}
func (m *TaskSummaryCounters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskSummaryCounters.Marshal(b, m, deterministic)
}
func (dst *TaskSummaryCounters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskSummaryCounters.Merge(dst, src)
}
func (m *TaskSummaryCounters) XXX_Size() int {
	return xxx_messageInfo_TaskSummaryCounters.Size(m)
}
func (m *TaskSummaryCounters) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskSummaryCounters.DiscardUnknown(m)
}

var xxx_messageInfo_TaskSummaryCounters proto.InternalMessageInfo

func (m *TaskSummaryCounters) GetCurrentlyActiveTasks() uint64 {
	if m != nil {
		return m.CurrentlyActiveTasks
	}
	return 0
}

func (m *TaskSummaryCounters) GetTotalActiveTasks() uint64 {
	if m != nil {
		return m.TotalActiveTasks
	}
	return 0
}

func (m *TaskSummaryCounters) GetTotalCollectRequests() uint64 {
	if m != nil {
		return m.TotalCollectRequests
	}
	return 0
}

type TaskDetailCounters struct {
	CollectRequests          uint64   `protobuf:"varint,1,opt,name=collectRequests,proto3" json:"collectRequests,omitempty"`
	TotalMetrics             uint64   `protobuf:"varint,2,opt,name=totalMetrics,proto3" json:"totalMetrics,omitempty"`
	AverageMetricsPerCollect uint64   `protobuf:"varint,3,opt,name=averageMetricsPerCollect,proto3" json:"averageMetricsPerCollect,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *TaskDetailCounters) Reset()         { *m = TaskDetailCounters{} }
func (m *TaskDetailCounters) String() string { return proto.CompactTextString(m) }
func (*TaskDetailCounters) ProtoMessage()    {}
func (*TaskDetailCounters) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{22}
}
func (m *TaskDetailCounters) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDetailCounters.Unmarshal(m, b)
}
func (m *TaskDetailCounters) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDetailCounters.Marshal(b, m, deterministic)
}
func (dst *TaskDetailCounters) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDetailCounters.Merge(dst, src)
}
func (m *TaskDetailCounters) XXX_Size() int {
	return xxx_messageInfo_TaskDetailCounters.Size(m)
}
func (m *TaskDetailCounters) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDetailCounters.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDetailCounters proto.InternalMessageInfo

func (m *TaskDetailCounters) GetCollectRequests() uint64 {
	if m != nil {
		return m.CollectRequests
	}
	return 0
}

func (m *TaskDetailCounters) GetTotalMetrics() uint64 {
	if m != nil {
		return m.TotalMetrics
	}
	return 0
}

func (m *TaskDetailCounters) GetAverageMetricsPerCollect() uint64 {
	if m != nil {
		return m.AverageMetricsPerCollect
	}
	return 0
}

type ProcessingTimes struct {
	Total                int64    `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Average              int64    `protobuf:"varint,2,opt,name=average,proto3" json:"average,omitempty"`
	Maximum              int64    `protobuf:"varint,3,opt,name=maximum,proto3" json:"maximum,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProcessingTimes) Reset()         { *m = ProcessingTimes{} }
func (m *ProcessingTimes) String() string { return proto.CompactTextString(m) }
func (*ProcessingTimes) ProtoMessage()    {}
func (*ProcessingTimes) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{23}
}
func (m *ProcessingTimes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessingTimes.Unmarshal(m, b)
}
func (m *ProcessingTimes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessingTimes.Marshal(b, m, deterministic)
}
func (dst *ProcessingTimes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessingTimes.Merge(dst, src)
}
func (m *ProcessingTimes) XXX_Size() int {
	return xxx_messageInfo_ProcessingTimes.Size(m)
}
func (m *ProcessingTimes) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessingTimes.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessingTimes proto.InternalMessageInfo

func (m *ProcessingTimes) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ProcessingTimes) GetAverage() int64 {
	if m != nil {
		return m.Average
	}
	return 0
}

func (m *ProcessingTimes) GetMaximum() int64 {
	if m != nil {
		return m.Maximum
	}
	return 0
}

type LastMeasurement struct {
	Occurred             *Time    `protobuf:"bytes,1,opt,name=occurred,proto3" json:"occurred,omitempty"`
	CollectedMetrics     uint64   `protobuf:"varint,2,opt,name=collectedMetrics,proto3" json:"collectedMetrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LastMeasurement) Reset()         { *m = LastMeasurement{} }
func (m *LastMeasurement) String() string { return proto.CompactTextString(m) }
func (*LastMeasurement) ProtoMessage()    {}
func (*LastMeasurement) Descriptor() ([]byte, []int) {
	return fileDescriptor_plugin_0a2a5c8fda85551d, []int{24}
}
func (m *LastMeasurement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LastMeasurement.Unmarshal(m, b)
}
func (m *LastMeasurement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LastMeasurement.Marshal(b, m, deterministic)
}
func (dst *LastMeasurement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LastMeasurement.Merge(dst, src)
}
func (m *LastMeasurement) XXX_Size() int {
	return xxx_messageInfo_LastMeasurement.Size(m)
}
func (m *LastMeasurement) XXX_DiscardUnknown() {
	xxx_messageInfo_LastMeasurement.DiscardUnknown(m)
}

var xxx_messageInfo_LastMeasurement proto.InternalMessageInfo

func (m *LastMeasurement) GetOccurred() *Time {
	if m != nil {
		return m.Occurred
	}
	return nil
}

func (m *LastMeasurement) GetCollectedMetrics() uint64 {
	if m != nil {
		return m.CollectedMetrics
	}
	return 0
}

func init() {
	proto.RegisterType((*PingRequest)(nil), "pluginrpc.PingRequest")
	proto.RegisterType((*PingResponse)(nil), "pluginrpc.PingResponse")
	proto.RegisterType((*KillRequest)(nil), "pluginrpc.KillRequest")
	proto.RegisterType((*KillResponse)(nil), "pluginrpc.KillResponse")
	proto.RegisterType((*CollectRequest)(nil), "pluginrpc.CollectRequest")
	proto.RegisterType((*CollectResponse)(nil), "pluginrpc.CollectResponse")
	proto.RegisterType((*LoadRequest)(nil), "pluginrpc.LoadRequest")
	proto.RegisterType((*LoadResponse)(nil), "pluginrpc.LoadResponse")
	proto.RegisterType((*UnloadRequest)(nil), "pluginrpc.UnloadRequest")
	proto.RegisterType((*UnloadResponse)(nil), "pluginrpc.UnloadResponse")
	proto.RegisterType((*InfoRequest)(nil), "pluginrpc.InfoRequest")
	proto.RegisterType((*InfoResponse)(nil), "pluginrpc.InfoResponse")
	proto.RegisterType((*Metric)(nil), "pluginrpc.Metric")
	proto.RegisterMapType((map[string]string)(nil), "pluginrpc.Metric.TagsEntry")
	proto.RegisterType((*Namespace)(nil), "pluginrpc.Namespace")
	proto.RegisterType((*MetricValue)(nil), "pluginrpc.MetricValue")
	proto.RegisterType((*Time)(nil), "pluginrpc.Time")
	proto.RegisterType((*Info)(nil), "pluginrpc.Info")
	proto.RegisterMapType((map[uint64]*TaskDetails)(nil), "pluginrpc.Info.TaskDetailsEntry")
	proto.RegisterType((*PluginInfo)(nil), "pluginrpc.PluginInfo")
	proto.RegisterType((*Options)(nil), "pluginrpc.Options")
	proto.RegisterType((*TaskSummary)(nil), "pluginrpc.TaskSummary")
	proto.RegisterType((*TaskDetails)(nil), "pluginrpc.TaskDetails")
	proto.RegisterType((*TaskSummaryCounters)(nil), "pluginrpc.TaskSummaryCounters")
	proto.RegisterType((*TaskDetailCounters)(nil), "pluginrpc.TaskDetailCounters")
	proto.RegisterType((*ProcessingTimes)(nil), "pluginrpc.ProcessingTimes")
	proto.RegisterType((*LastMeasurement)(nil), "pluginrpc.LastMeasurement")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ControllerClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error)
}

type controllerClient struct {
	cc *grpc.ClientConn
}

func NewControllerClient(cc *grpc.ClientConn) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, "/pluginrpc.Controller/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) Kill(ctx context.Context, in *KillRequest, opts ...grpc.CallOption) (*KillResponse, error) {
	out := new(KillResponse)
	err := c.cc.Invoke(ctx, "/pluginrpc.Controller/Kill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ControllerServer is the server API for Controller service.
type ControllerServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	Kill(context.Context, *KillRequest) (*KillResponse, error)
}

func RegisterControllerServer(s *grpc.Server, srv ControllerServer) {
	s.RegisterService(&_Controller_serviceDesc, srv)
}

func _Controller_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginrpc.Controller/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_Kill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Kill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginrpc.Controller/Kill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Kill(ctx, req.(*KillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Controller_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pluginrpc.Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Controller_Ping_Handler,
		},
		{
			MethodName: "Kill",
			Handler:    _Controller_Kill_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

// CollectorClient is the client API for Collector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CollectorClient interface {
	Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (Collector_CollectClient, error)
	Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error)
	Unload(ctx context.Context, in *UnloadRequest, opts ...grpc.CallOption) (*UnloadResponse, error)
	Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error)
}

type collectorClient struct {
	cc *grpc.ClientConn
}

func NewCollectorClient(cc *grpc.ClientConn) CollectorClient {
	return &collectorClient{cc}
}

func (c *collectorClient) Collect(ctx context.Context, in *CollectRequest, opts ...grpc.CallOption) (Collector_CollectClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Collector_serviceDesc.Streams[0], "/pluginrpc.Collector/Collect", opts...)
	if err != nil {
		return nil, err
	}
	x := &collectorCollectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Collector_CollectClient interface {
	Recv() (*CollectResponse, error)
	grpc.ClientStream
}

type collectorCollectClient struct {
	grpc.ClientStream
}

func (x *collectorCollectClient) Recv() (*CollectResponse, error) {
	m := new(CollectResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *collectorClient) Load(ctx context.Context, in *LoadRequest, opts ...grpc.CallOption) (*LoadResponse, error) {
	out := new(LoadResponse)
	err := c.cc.Invoke(ctx, "/pluginrpc.Collector/Load", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorClient) Unload(ctx context.Context, in *UnloadRequest, opts ...grpc.CallOption) (*UnloadResponse, error) {
	out := new(UnloadResponse)
	err := c.cc.Invoke(ctx, "/pluginrpc.Collector/Unload", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *collectorClient) Info(ctx context.Context, in *InfoRequest, opts ...grpc.CallOption) (*InfoResponse, error) {
	out := new(InfoResponse)
	err := c.cc.Invoke(ctx, "/pluginrpc.Collector/Info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CollectorServer is the server API for Collector service.
type CollectorServer interface {
	Collect(*CollectRequest, Collector_CollectServer) error
	Load(context.Context, *LoadRequest) (*LoadResponse, error)
	Unload(context.Context, *UnloadRequest) (*UnloadResponse, error)
	Info(context.Context, *InfoRequest) (*InfoResponse, error)
}

func RegisterCollectorServer(s *grpc.Server, srv CollectorServer) {
	s.RegisterService(&_Collector_serviceDesc, srv)
}

func _Collector_Collect_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(CollectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CollectorServer).Collect(m, &collectorCollectServer{stream})
}

type Collector_CollectServer interface {
	Send(*CollectResponse) error
	grpc.ServerStream
}

type collectorCollectServer struct {
	grpc.ServerStream
}

func (x *collectorCollectServer) Send(m *CollectResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Collector_Load_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).Load(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginrpc.Collector/Load",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).Load(ctx, req.(*LoadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collector_Unload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).Unload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginrpc.Collector/Unload",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).Unload(ctx, req.(*UnloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Collector_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CollectorServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginrpc.Collector/Info",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CollectorServer).Info(ctx, req.(*InfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Collector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pluginrpc.Collector",
	HandlerType: (*CollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Load",
			Handler:    _Collector_Load_Handler,
		},
		{
			MethodName: "Unload",
			Handler:    _Collector_Unload_Handler,
		},
		{
			MethodName: "Info",
			Handler:    _Collector_Info_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Collect",
			Handler:       _Collector_Collect_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "plugin.proto",
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_plugin_0a2a5c8fda85551d) }

var fileDescriptor_plugin_0a2a5c8fda85551d = []byte{
	// 1321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x57, 0x5d, 0x6f, 0x1b, 0x45,
	0x17, 0xee, 0xda, 0x8e, 0xed, 0x3d, 0x4e, 0xe2, 0x74, 0xde, 0xbe, 0xed, 0xd6, 0x7d, 0x5f, 0xb0,
	0x16, 0x04, 0x2e, 0x84, 0x50, 0xb9, 0x21, 0x2d, 0x95, 0xb8, 0x20, 0x29, 0xa8, 0x11, 0x09, 0x44,
	0x93, 0xb6, 0x5c, 0x70, 0x61, 0x4d, 0xd6, 0x13, 0x6b, 0xdb, 0xf5, 0x8e, 0x99, 0x99, 0x5d, 0x35,
	0x37, 0x88, 0x7f, 0xc0, 0x05, 0x12, 0x97, 0xdc, 0xf3, 0x13, 0x10, 0xe2, 0x37, 0xf1, 0x17, 0xd0,
	0x7c, 0xec, 0x7a, 0xd6, 0xde, 0xf2, 0x71, 0xb7, 0xe7, 0x3c, 0xcf, 0xf9, 0x98, 0x33, 0xe7, 0x78,
	0x8e, 0x61, 0x73, 0x91, 0x64, 0xb3, 0x38, 0xdd, 0x5b, 0x70, 0x26, 0x19, 0xf2, 0x8d, 0xc4, 0x17,
	0x51, 0xb8, 0x05, 0xbd, 0xb3, 0x38, 0x9d, 0x61, 0xfa, 0x6d, 0x46, 0x85, 0x0c, 0xb7, 0x61, 0xd3,
	0x88, 0x62, 0xc1, 0x52, 0x41, 0x15, 0xfc, 0x45, 0x9c, 0x24, 0x0e, 0x6c, 0x44, 0x0b, 0xdf, 0x85,
	0xed, 0x23, 0x96, 0x24, 0x34, 0x92, 0x96, 0x81, 0x6e, 0x41, 0x47, 0x12, 0xf1, 0x72, 0x12, 0x4f,
	0x03, 0x6f, 0xe8, 0x8d, 0x36, 0x70, 0x5b, 0x89, 0xc7, 0xd3, 0xf0, 0x08, 0xfa, 0x25, 0xd5, 0x58,
	0xa3, 0x7b, 0x00, 0x73, 0x2a, 0x79, 0x1c, 0x4d, 0x04, 0x95, 0x81, 0x37, 0x6c, 0x8e, 0x7a, 0xe3,
	0xeb, 0x7b, 0x65, 0x6e, 0x7b, 0xa7, 0x1a, 0xc4, 0xbe, 0x21, 0x9d, 0x53, 0x19, 0x72, 0xe8, 0x9d,
	0x30, 0x32, 0xfd, 0xbb, 0x60, 0xe8, 0x4d, 0xe8, 0xbd, 0x10, 0x2c, 0x9d, 0x44, 0x2c, 0xbd, 0x8c,
	0x67, 0x41, 0x63, 0xe8, 0x8d, 0x36, 0x31, 0x28, 0xd5, 0x91, 0xd6, 0xa0, 0xbb, 0xb0, 0x53, 0x86,
	0x56, 0x39, 0x31, 0x2e, 0x82, 0xe6, 0xb0, 0x39, 0xf2, 0x71, 0xbf, 0x88, 0x66, 0xd5, 0xea, 0xcc,
	0x26, 0xa6, 0x3d, 0xf3, 0x08, 0xb6, 0x9e, 0xa5, 0xc9, 0x3f, 0xc8, 0x22, 0xdc, 0x81, 0xed, 0x82,
	0xb9, 0x2c, 0xe7, 0x71, 0x7a, 0xc9, 0x8a, 0x72, 0xde, 0x87, 0x4d, 0x23, 0xda, 0x82, 0xbc, 0x05,
	0xad, 0x38, 0xbd, 0x64, 0xda, 0x4d, 0x6f, 0xdc, 0x77, 0x4a, 0xa1, 0x69, 0x1a, 0x0c, 0x7f, 0x6d,
	0x40, 0xdb, 0x54, 0x06, 0x8d, 0xc1, 0x4f, 0xc9, 0x9c, 0x8a, 0x05, 0x89, 0xa8, 0xad, 0xdf, 0x0d,
	0xc7, 0xe8, 0xcb, 0x02, 0xc3, 0x4b, 0x1a, 0xda, 0x85, 0x8d, 0x9c, 0x24, 0x19, 0xd5, 0x45, 0xe9,
	0x8d, 0x6f, 0xae, 0xd5, 0xfb, 0xb9, 0x42, 0xb1, 0x21, 0xa1, 0x0f, 0xa1, 0x25, 0xc9, 0xcc, 0xd4,
	0xa6, 0x37, 0xbe, 0xb3, 0x46, 0xde, 0x7b, 0x4a, 0x66, 0xe2, 0xb3, 0x54, 0xf2, 0x2b, 0xac, 0x89,
	0xe8, 0x03, 0xf0, 0x65, 0x3c, 0xa7, 0x42, 0x92, 0xf9, 0x22, 0x68, 0xad, 0x9d, 0xe3, 0x69, 0x3c,
	0xa7, 0x78, 0xc9, 0x40, 0x43, 0xe8, 0x4d, 0xa9, 0x88, 0x78, 0xbc, 0x90, 0x31, 0x4b, 0x83, 0x8d,
	0xa1, 0x37, 0xf2, 0xb1, 0xab, 0x42, 0x08, 0x5a, 0x59, 0x1a, 0xcb, 0xa0, 0xad, 0x21, 0xfd, 0x3d,
	0x78, 0x00, 0x7e, 0x19, 0x17, 0xed, 0x40, 0xf3, 0x25, 0xbd, 0xd2, 0x35, 0xf3, 0xb1, 0xfa, 0x44,
	0x37, 0xdc, 0x23, 0xfa, 0xf6, 0x28, 0x8f, 0x1a, 0x0f, 0xbd, 0xf0, 0x6b, 0xf0, 0xcb, 0xa2, 0x28,
	0xcf, 0xaa, 0x2c, 0xd6, 0x52, 0x7f, 0xd7, 0x9b, 0xae, 0x66, 0xd9, 0x5c, 0xcb, 0x32, 0xfc, 0xa9,
	0x01, 0x3d, 0xa7, 0x7c, 0xe8, 0x36, 0x74, 0xf2, 0xc9, 0x65, 0xc2, 0x88, 0xd4, 0xee, 0x1b, 0x4f,
	0xae, 0xe1, 0x76, 0xfe, 0xb9, 0x92, 0xd1, 0x1d, 0xe8, 0xe6, 0x93, 0x29, 0xcb, 0x2e, 0x12, 0x13,
	0xc5, 0x7b, 0x72, 0x0d, 0x77, 0xf2, 0xc7, 0x5a, 0x61, 0xec, 0xe2, 0x54, 0xde, 0x1f, 0xeb, 0x28,
	0x1b, 0xda, 0xee, 0x58, 0xc9, 0x25, 0x74, 0xb0, 0xaf, 0xeb, 0xda, 0x2c, 0xa0, 0x83, 0x7d, 0xe3,
	0x32, 0x33, 0x66, 0xaa, 0x84, 0x5b, 0xda, 0xe5, 0x33, 0xad, 0x58, 0x82, 0x07, 0xfb, 0xba, 0x88,
	0xad, 0x12, 0x3c, 0xd8, 0x47, 0xb7, 0xa0, 0x9d, 0x4f, 0x2e, 0x18, 0x4b, 0x82, 0xce, 0xd0, 0x1b,
	0x75, 0x9f, 0x5c, 0xc3, 0x1b, 0xf9, 0x21, 0x63, 0x89, 0x89, 0x76, 0x71, 0x25, 0xa9, 0x08, 0xba,
	0x6a, 0x7a, 0x74, 0xb4, 0x43, 0x25, 0x1b, 0x87, 0x42, 0xf2, 0x38, 0x9d, 0x05, 0xbe, 0x2a, 0x85,
	0x76, 0x78, 0xae, 0x15, 0x87, 0xdb, 0xb0, 0x39, 0x25, 0x92, 0x4c, 0x72, 0xc2, 0x63, 0x92, 0xca,
	0x70, 0x17, 0x5a, 0xea, 0xce, 0xd5, 0x2d, 0x09, 0x1a, 0xe9, 0x62, 0x34, 0xb1, 0xfa, 0xd4, 0xe5,
	0x57, 0xaa, 0x86, 0x56, 0xe9, 0xef, 0xf0, 0xc7, 0x06, 0xb4, 0x54, 0xab, 0xa3, 0x8f, 0x00, 0x4c,
	0xd3, 0x1c, 0x2f, 0xe7, 0xe1, 0xbf, 0x4e, 0x1f, 0x9d, 0x95, 0x20, 0x76, 0x88, 0xe8, 0x21, 0xf4,
	0xd4, 0xec, 0x9d, 0x67, 0xf3, 0x39, 0xe1, 0x57, 0x35, 0x2d, 0xfe, 0x74, 0x89, 0x62, 0x97, 0x8a,
	0x0e, 0x8d, 0xe5, 0x63, 0x2a, 0x49, 0x9c, 0x14, 0xfd, 0x3e, 0x5c, 0x99, 0x40, 0x6d, 0x6e, 0x29,
	0xa6, 0xe9, 0x5d, 0xa3, 0xc1, 0x73, 0xd8, 0x59, 0x25, 0xb8, 0xdd, 0xd9, 0x32, 0xdd, 0xf9, 0x17,
	0x03, 0xe8, 0x58, 0xbb, 0x5d, 0xfb, 0x9b, 0x07, 0xb0, 0x3c, 0x70, 0x6d, 0xdf, 0x06, 0xd0, 0xc9,
	0x29, 0x17, 0xaa, 0x3b, 0x4d, 0xe7, 0x16, 0x22, 0x7a, 0x07, 0xb6, 0xa3, 0xf9, 0xf4, 0x24, 0x4e,
	0xe9, 0x57, 0xba, 0x55, 0x85, 0x6d, 0xdf, 0x15, 0x2d, 0xda, 0x85, 0x0e, 0xb3, 0x04, 0x33, 0xb6,
	0xc8, 0x49, 0xcc, 0x92, 0x70, 0x41, 0x41, 0x77, 0xa1, 0x23, 0x24, 0xe1, 0x92, 0x4e, 0x75, 0xc3,
	0xd5, 0x0c, 0x79, 0x81, 0x87, 0x7f, 0x34, 0xa0, 0x53, 0x04, 0x19, 0x40, 0xd7, 0xde, 0xd6, 0x99,
	0x4d, 0xbf, 0x94, 0x15, 0x36, 0xe3, 0x8b, 0xe8, 0x8c, 0x71, 0xa9, 0xcf, 0xb0, 0x85, 0x4b, 0x19,
	0xfd, 0x0f, 0xfc, 0xc5, 0x82, 0xb3, 0x4b, 0x0d, 0x36, 0x35, 0xb8, 0x54, 0x28, 0x54, 0x48, 0x22,
	0x85, 0x46, 0x5b, 0x06, 0x2d, 0x15, 0x68, 0x04, 0x7d, 0xed, 0x27, 0x4e, 0x67, 0x2a, 0x31, 0x96,
	0x49, 0x9d, 0x72, 0x13, 0xaf, 0xaa, 0xd1, 0x2e, 0x5c, 0x2f, 0x54, 0xa7, 0xe4, 0xd5, 0x69, 0x2c,
	0x04, 0x9d, 0x9a, 0x91, 0xc1, 0xeb, 0x80, 0xca, 0x37, 0x61, 0xb3, 0x13, 0x9a, 0x53, 0x33, 0x3c,
	0x3e, 0x2e, 0x65, 0xe5, 0x89, 0xa6, 0xe4, 0x22, 0xa1, 0x67, 0x2a, 0xc9, 0x73, 0xca, 0x73, 0xca,
	0xf5, 0x1c, 0x75, 0xf1, 0x3a, 0xa0, 0x7e, 0x5e, 0x8c, 0xf2, 0x5c, 0x25, 0xad, 0x67, 0xaa, 0x8b,
	0x5d, 0xd5, 0xd2, 0x9f, 0x16, 0xad, 0x3f, 0x70, 0xfd, 0x39, 0x40, 0xf8, 0x83, 0x07, 0x3d, 0xa7,
	0xd1, 0xd1, 0x23, 0xe8, 0x46, 0x2c, 0x4b, 0x25, 0xe5, 0xc2, 0x8e, 0xd2, 0x1b, 0xf5, 0x23, 0x71,
	0x64, 0x59, 0xb8, 0xe4, 0xa3, 0xc7, 0xd0, 0x5f, 0x70, 0x16, 0x51, 0x21, 0x6c, 0xa1, 0x84, 0xed,
	0xdb, 0x81, 0x3b, 0x8d, 0x55, 0x06, 0x5e, 0x35, 0x09, 0x7f, 0x6f, 0x98, 0x8c, 0x6c, 0x73, 0xa3,
	0xb7, 0x61, 0xcb, 0x3c, 0xcd, 0x19, 0x27, 0xfa, 0x27, 0xd5, 0x34, 0x43, 0x55, 0xa9, 0x9a, 0xfa,
	0x32, 0x4e, 0x74, 0xda, 0x0d, 0xfd, 0x36, 0x17, 0x22, 0xfa, 0xd8, 0x39, 0x51, 0x53, 0xa7, 0xf3,
	0xff, 0xda, 0x31, 0xaa, 0x39, 0xd0, 0xbb, 0xd0, 0x56, 0x4f, 0x32, 0x9d, 0xbe, 0xee, 0x75, 0xb2,
	0x70, 0xdd, 0xc9, 0x37, 0xfe, 0xf5, 0xc9, 0x95, 0x97, 0x84, 0x08, 0x79, 0x4a, 0x89, 0xc8, 0x38,
	0x9d, 0xd3, 0xd4, 0xbc, 0x64, 0x55, 0x2f, 0x27, 0x55, 0x06, 0x5e, 0x35, 0x09, 0x7f, 0xf1, 0xe0,
	0x3f, 0x35, 0xf7, 0x84, 0xc6, 0x70, 0x23, 0xca, 0x38, 0xa7, 0xa9, 0x4c, 0xae, 0x3e, 0x8d, 0x64,
	0x9c, 0x53, 0xc5, 0x12, 0xf6, 0xe7, 0xa6, 0x16, 0x43, 0xef, 0xc1, 0x8e, 0x64, 0x92, 0x24, 0x2e,
	0xbf, 0xa1, 0xf9, 0x6b, 0x7a, 0xe5, 0x5f, 0xeb, 0xaa, 0x4b, 0x9e, 0xa9, 0x79, 0x0b, 0xd7, 0x62,
	0xe1, 0xcf, 0x1e, 0xa0, 0xf5, 0x1b, 0x50, 0x63, 0x18, 0xad, 0x78, 0x31, 0x59, 0xae, 0xaa, 0x51,
	0x08, 0x9b, 0xda, 0xb1, 0x79, 0x4f, 0x8b, 0xe4, 0x2a, 0x3a, 0xf4, 0x08, 0x02, 0x92, 0x53, 0x4e,
	0x66, 0xd4, 0x6a, 0xce, 0x28, 0xb7, 0x89, 0xd8, 0xe4, 0x5e, 0x8b, 0x87, 0xdf, 0x40, 0x7f, 0xe5,
	0xda, 0xd4, 0xb3, 0xaf, 0xdd, 0xdb, 0xf7, 0xc9, 0x08, 0xaa, 0xff, 0xac, 0x13, 0xfb, 0x48, 0x15,
	0xa2, 0x42, 0xe6, 0xe4, 0x55, 0x3c, 0xcf, 0xe6, 0x3a, 0x5a, 0x13, 0x17, 0x62, 0xf8, 0x02, 0xfa,
	0x2b, 0xb7, 0x89, 0xde, 0x87, 0x2e, 0x8b, 0xf4, 0x55, 0x4c, 0x6b, 0x36, 0x3b, 0xdd, 0x73, 0x25,
	0x41, 0xdd, 0x8e, 0xad, 0x07, 0x9d, 0x56, 0x0b, 0xb0, 0xa6, 0x1f, 0x7f, 0x07, 0x70, 0xc4, 0x52,
	0xc9, 0x95, 0x9e, 0xa3, 0x07, 0xd0, 0x52, 0x3f, 0x50, 0xc8, 0x7d, 0x50, 0x9c, 0xd5, 0x7e, 0x70,
	0x6b, 0x4d, 0x6f, 0xb7, 0xce, 0x07, 0xd0, 0x52, 0x4b, 0x7d, 0xc5, 0xd0, 0x59, 0xfa, 0x2b, 0x86,
	0xee, 0xf6, 0x3f, 0xfe, 0xbe, 0x01, 0xbe, 0x2d, 0x2a, 0xe3, 0xe8, 0x10, 0x3a, 0x56, 0x40, 0xb7,
	0x1d, 0x8b, 0x6a, 0x7b, 0x0c, 0x06, 0x75, 0x90, 0xf1, 0x77, 0xcf, 0x53, 0xa9, 0xa8, 0x5d, 0xbb,
	0x92, 0x8a, 0xb3, 0xf0, 0x57, 0x52, 0x71, 0x97, 0x72, 0xf4, 0x09, 0xb4, 0xcd, 0xaa, 0x8d, 0x02,
	0x87, 0x52, 0xd9, 0xd3, 0x07, 0xb7, 0x6b, 0x90, 0x65, 0x09, 0xf4, 0xd3, 0x7a, 0x73, 0x75, 0xe5,
	0xae, 0x89, 0xeb, 0x6e, 0xec, 0x17, 0x6d, 0xfd, 0x87, 0xea, 0xfe, 0x9f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xa8, 0x2f, 0xfb, 0x3e, 0x60, 0x0d, 0x00, 0x00,
}
